
package com.mrted.ws.position;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PositionWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PositionWebService {


    /**
     * 
     * @param position
     */
    @WebMethod
    @RequestWrapper(localName = "createPosition", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.CreatePosition")
    @ResponseWrapper(localName = "createPositionResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.CreatePositionResponse")
    public void createPosition(
        @WebParam(name = "position", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<PositionDto> position);

    /**
     * 
     * @param organizationLevel
     * @return
     *     returns com.mrted.ws.position.OrganizationStructureDto
     */
    @WebMethod
    @WebResult(name = "organizationStructure", targetNamespace = "")
    @RequestWrapper(localName = "getOrganizationStructure", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetOrganizationStructure")
    @ResponseWrapper(localName = "getOrganizationStructureResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetOrganizationStructureResponse")
    public OrganizationStructureDto getOrganizationStructure(
        @WebParam(name = "organizationLevel", targetNamespace = "")
        Integer organizationLevel);

    /**
     * 
     * @param id
     * @return
     *     returns com.mrted.ws.position.PositionDto
     */
    @WebMethod
    @WebResult(name = "position", targetNamespace = "")
    @RequestWrapper(localName = "getPositionById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionById")
    @ResponseWrapper(localName = "getPositionByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionByIdResponse")
    public PositionDto getPositionById(
        @WebParam(name = "id", targetNamespace = "")
        long id);

    /**
     * 
     * @param requestbyobsid
     * @return
     *     returns java.util.List<com.mrted.ws.position.PositionsByObsIdResponseDto>
     */
    @WebMethod
    @WebResult(name = "positionsByObsIdResponseDto", targetNamespace = "")
    @RequestWrapper(localName = "getPositionsByObsId", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionsByObsId")
    @ResponseWrapper(localName = "getPositionsByObsIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionsByObsIdResponse")
    public List<PositionsByObsIdResponseDto> getPositionsByObsId(
        @WebParam(name = "requestbyobsid", targetNamespace = "")
        RequestbyobsidDto requestbyobsid);

    /**
     * 
     * @param pageNumber
     * @param orgId
     * @param status
     * @return
     *     returns java.util.List<com.mrted.ws.position.PositionDto>
     */
    @WebMethod
    @WebResult(name = "position", targetNamespace = "")
    @RequestWrapper(localName = "getPositions", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositions")
    @ResponseWrapper(localName = "getPositionsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionsResponse")
    public List<PositionDto> getPositions(
        @WebParam(name = "orgId", targetNamespace = "")
        Long orgId,
        @WebParam(name = "status", targetNamespace = "")
        String status,
        @WebParam(name = "pageNumber", targetNamespace = "")
        Integer pageNumber);

    /**
     * 
     * @param pageNumber
     * @param departmentId
     * @return
     *     returns java.util.List<com.mrted.ws.position.JobLocationDto>
     */
    @WebMethod
    @WebResult(name = "locations", targetNamespace = "")
    @RequestWrapper(localName = "getLocations", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetLocations")
    @ResponseWrapper(localName = "getLocationsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetLocationsResponse")
    public List<JobLocationDto> getLocations(
        @WebParam(name = "departmentId", targetNamespace = "")
        Long departmentId,
        @WebParam(name = "pageNumber", targetNamespace = "")
        Integer pageNumber);

    /**
     * 
     * @param reqNumber
     * @return
     *     returns java.util.List<com.mrted.ws.position.PositionDto>
     */
    @WebMethod
    @WebResult(name = "position", targetNamespace = "")
    @RequestWrapper(localName = "getPositionsByReqNumber", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionsByReqNumber")
    @ResponseWrapper(localName = "getPositionsByReqNumberResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionsByReqNumberResponse")
    public List<PositionDto> getPositionsByReqNumber(
        @WebParam(name = "reqNumber", targetNamespace = "")
        String reqNumber);

    /**
     * 
     * @param jobNumber
     * @return
     *     returns java.util.List<com.mrted.ws.position.PositionDto>
     */
    @WebMethod
    @WebResult(name = "position", targetNamespace = "")
    @RequestWrapper(localName = "getPositionByExternalJobNumber", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionByExternalJobNumber")
    @ResponseWrapper(localName = "getPositionByExternalJobNumberResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionByExternalJobNumberResponse")
    public List<PositionDto> getPositionByExternalJobNumber(
        @WebParam(name = "jobNumber", targetNamespace = "")
        String jobNumber);

    /**
     * 
     * @param position
     */
    @WebMethod
    @RequestWrapper(localName = "updatePosition", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.UpdatePosition")
    @ResponseWrapper(localName = "updatePositionResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.UpdatePositionResponse")
    public void updatePosition(
        @WebParam(name = "position", targetNamespace = "")
        PositionDto position);

    /**
     * 
     * @param requestparam
     * @return
     *     returns java.util.List<com.mrted.ws.position.PositionDto>
     */
    @WebMethod
    @WebResult(name = "position", targetNamespace = "")
    @RequestWrapper(localName = "getPositionsByUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionsByUser")
    @ResponseWrapper(localName = "getPositionsByUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionsByUserResponse")
    public List<PositionDto> getPositionsByUser(
        @WebParam(name = "requestparam", targetNamespace = "")
        RequestParamsDto requestparam);

    /**
     * 
     * @param requestbyteammember
     * @return
     *     returns java.util.List<com.mrted.ws.position.PositionDto>
     */
    @WebMethod
    @WebResult(name = "position", targetNamespace = "")
    @RequestWrapper(localName = "getPositionByTeamMember", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionByTeamMember")
    @ResponseWrapper(localName = "getPositionByTeamMemberResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.position.GetPositionByTeamMemberResponse")
    public List<PositionDto> getPositionByTeamMember(
        @WebParam(name = "requestbyteammember", targetNamespace = "")
        RequestByTeamMemberDto requestbyteammember);

}
