
package com.mrted.ws.position;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PositionWebService", targetNamespace = "http://ws.mrted.com/", wsdlLocation = "https://api3.lumesse-talenthub.com/HRIS/SOAP/Position?wsdl")
@HandlerChain(file="handler-chain.xml")
public class PositionWebService_Service
    extends Service
{

    private final static URL POSITIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException POSITIONWEBSERVICE_EXCEPTION;
    private final static QName POSITIONWEBSERVICE_QNAME = new QName("http://ws.mrted.com/", "PositionWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api3.lumesse-talenthub.com/HRIS/SOAP/Position?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POSITIONWEBSERVICE_WSDL_LOCATION = url;
        POSITIONWEBSERVICE_EXCEPTION = e;
    }

    public PositionWebService_Service() {
        super(__getWsdlLocation(), POSITIONWEBSERVICE_QNAME);
    }

    public PositionWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), POSITIONWEBSERVICE_QNAME, features);
    }

    public PositionWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, POSITIONWEBSERVICE_QNAME);
    }

    public PositionWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POSITIONWEBSERVICE_QNAME, features);
    }

    public PositionWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PositionWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PositionWebService
     */
    @WebEndpoint(name = "PositionWebServicePort")
    public PositionWebService getPositionWebServicePort() {
        return super.getPort(new QName("http://ws.mrted.com/", "PositionWebServicePort"), PositionWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PositionWebService
     */
    @WebEndpoint(name = "PositionWebServicePort")
    public PositionWebService getPositionWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mrted.com/", "PositionWebServicePort"), PositionWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POSITIONWEBSERVICE_EXCEPTION!= null) {
            throw POSITIONWEBSERVICE_EXCEPTION;
        }
        return POSITIONWEBSERVICE_WSDL_LOCATION;
    }

}
