
package com.mrted.ws.user;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserWebService {


    /**
     * 
     * @param activationType
     * @param password
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "activateUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.ActivateUser")
    @ResponseWrapper(localName = "activateUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.ActivateUserResponse")
    public void activateUser(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "password", targetNamespace = "")
        String password,
        @WebParam(name = "activationType", targetNamespace = "http://ws.mrted.com/")
        String activationType);

    /**
     * 
     * @param tagTypeName
     * @param tagName
     * @param userId
     */
    @WebMethod
    @RequestWrapper(localName = "addTag", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.AddTag")
    @ResponseWrapper(localName = "addTagResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.AddTagResponse")
    public void addTag(
        @WebParam(name = "userId", targetNamespace = "http://ws.mrted.com/")
        Long userId,
        @WebParam(name = "tagName", targetNamespace = "http://ws.mrted.com/")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

    /**
     * 
     * @param roleId
     * @param userId
     * @param departmentIdList
     */
    @WebMethod
    @RequestWrapper(localName = "assignRole", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.AssignRole")
    @ResponseWrapper(localName = "assignRoleResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.AssignRoleResponse")
    public void assignRole(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId,
        @WebParam(name = "roleId", targetNamespace = "")
        Long roleId,
        @WebParam(name = "departmentIdList", targetNamespace = "")
        String departmentIdList);

    /**
     * 
     * @param tagTypeName
     * @param tagName
     * @param userId
     * @param departmentIdList
     */
    @WebMethod
    @RequestWrapper(localName = "assignRolesWithTag", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.AssignRolesWithTag")
    @ResponseWrapper(localName = "assignRolesWithTagResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.AssignRolesWithTagResponse")
    public void assignRolesWithTag(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId,
        @WebParam(name = "tagName", targetNamespace = "")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "")
        String tagTypeName,
        @WebParam(name = "departmentIdList", targetNamespace = "")
        String departmentIdList);

    /**
     * 
     * @param password
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "changePassword", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.ChangePassword")
    @ResponseWrapper(localName = "changePasswordResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.ChangePasswordResponse")
    public void changePassword(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "password", targetNamespace = "")
        String password);

    /**
     * 
     * @param userId
     */
    @WebMethod
    @RequestWrapper(localName = "clearAllRoleAssignments", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.ClearAllRoleAssignments")
    @ResponseWrapper(localName = "clearAllRoleAssignmentsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.ClearAllRoleAssignmentsResponse")
    public void clearAllRoleAssignments(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId);

    /**
     * 
     * @param configuration
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "configureUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.ConfigureUser")
    @ResponseWrapper(localName = "configureUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.ConfigureUserResponse")
    public void configureUser(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "configuration", targetNamespace = "")
        List<UserConfigParametersDto> configuration);

    /**
     * 
     * @param activationType
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "createUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.CreateUser")
    @ResponseWrapper(localName = "createUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.CreateUserResponse")
    public void createUser(
        @WebParam(name = "user", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<UserExtDto> user,
        @WebParam(name = "activationType", targetNamespace = "http://ws.mrted.com/")
        String activationType);

    /**
     * 
     * @param id
     */
    @WebMethod
    @RequestWrapper(localName = "deactivateUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.DeactivateUser")
    @ResponseWrapper(localName = "deactivateUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.DeactivateUserResponse")
    public void deactivateUser(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(name = "generatedPassword", targetNamespace = "")
    @RequestWrapper(localName = "generatePassword", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GeneratePassword")
    @ResponseWrapper(localName = "generatePasswordResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GeneratePasswordResponse")
    public String generatePassword();

    /**
     * 
     * @param userLogin
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateTemporaryPassword", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GenerateTemporaryPassword")
    @ResponseWrapper(localName = "generateTemporaryPasswordResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GenerateTemporaryPasswordResponse")
    public String generateTemporaryPassword(
        @WebParam(name = "userLogin", targetNamespace = "http://ws.mrted.com/")
        String userLogin);

    /**
     * 
     * @return
     *     returns com.mrted.ws.user.UserExtDto
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getCurrentUserExt", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetCurrentUserExt")
    @ResponseWrapper(localName = "getCurrentUserExtResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetCurrentUserExtResponse")
    public UserExtDto getCurrentUserExt();

    /**
     * 
     * @return
     *     returns java.util.List<com.mrted.ws.user.StringArray>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getGrantedPools", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetGrantedPools")
    @ResponseWrapper(localName = "getGrantedPoolsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetGrantedPoolsResponse")
    public List<StringArray> getGrantedPools();

    /**
     * 
     * @param departmentId
     * @return
     *     returns java.util.List<java.lang.Long>
     */
    @WebMethod
    @WebResult(name = "rights", targetNamespace = "")
    @RequestWrapper(localName = "getRightsForDepartmentAndCurrentUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetRightsForDepartmentAndCurrentUser")
    @ResponseWrapper(localName = "getRightsForDepartmentAndCurrentUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetRightsForDepartmentAndCurrentUserResponse")
    public List<Long> getRightsForDepartmentAndCurrentUser(
        @WebParam(name = "departmentId", targetNamespace = "")
        Long departmentId);

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<com.mrted.ws.user.RoleAssignmentDto>
     */
    @WebMethod
    @WebResult(name = "userRoleAssignment", targetNamespace = "")
    @RequestWrapper(localName = "getRolesAssignedForUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetRolesAssignedForUser")
    @ResponseWrapper(localName = "getRolesAssignedForUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetRolesAssignedForUserResponse")
    public List<RoleAssignmentDto> getRolesAssignedForUser(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId);

    /**
     * 
     * @return
     *     returns java.util.List<com.mrted.ws.user.TagType>
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTagTypes", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetTagTypes")
    @ResponseWrapper(localName = "getTagTypesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetTagTypesResponse")
    public List<TagType> getTagTypes();

    /**
     * 
     * @param tagTypeName
     * @param tagName
     * @return
     *     returns java.util.List<com.mrted.ws.user.UserDto>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTaggedUsers", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetTaggedUsers")
    @ResponseWrapper(localName = "getTaggedUsersResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetTaggedUsersResponse")
    public List<UserDto> getTaggedUsers(
        @WebParam(name = "tagName", targetNamespace = "http://ws.mrted.com/")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

    /**
     * 
     * @param tagTypeName
     * @return
     *     returns java.util.List<com.mrted.ws.user.Tag>
     */
    @WebMethod
    @WebResult(name = "tag", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTagsForType", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetTagsForType")
    @ResponseWrapper(localName = "getTagsForTypeResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetTagsForTypeResponse")
    public List<Tag> getTagsForType(
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

    /**
     * 
     * @param id
     * @return
     *     returns com.mrted.ws.user.UserDto
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getUserById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetUserById")
    @ResponseWrapper(localName = "getUserByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetUserByIdResponse")
    public UserDto getUserById(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param userId
     * @return
     *     returns java.util.List<com.mrted.ws.user.UserDataSoapDto>
     */
    @WebMethod
    @WebResult(name = "userData", targetNamespace = "")
    @RequestWrapper(localName = "getUserData", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetUserData")
    @ResponseWrapper(localName = "getUserDataResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetUserDataResponse")
    public List<UserDataSoapDto> getUserData(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId);

    /**
     * 
     * @param id
     * @return
     *     returns com.mrted.ws.user.UserExtDto
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getUserExtById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetUserExtById")
    @ResponseWrapper(localName = "getUserExtByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetUserExtByIdResponse")
    public UserExtDto getUserExtById(
        @WebParam(name = "id", targetNamespace = "")
        Long id);

    /**
     * 
     * @param requestByGetUsersDto
     * @return
     *     returns java.util.List<com.mrted.ws.user.UserDto>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getUsers", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetUsers")
    @ResponseWrapper(localName = "getUsersResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetUsersResponse")
    public List<UserDto> getUsers(
        @WebParam(name = "requestByGetUsersDto", targetNamespace = "")
        RequestByGetUsersDto requestByGetUsersDto);

    /**
     * 
     * @return
     *     returns java.util.List<com.mrted.ws.user.UserDto>
     */
    @WebMethod
    @WebResult(name = "user", targetNamespace = "")
    @RequestWrapper(localName = "getInactiveUsers", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetInactiveUsers")
    @ResponseWrapper(localName = "getInactiveUsersResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetInactiveUsersResponse")
    public List<UserDto> getInactiveUsers();

    /**
     * 
     * @param userId
     */
    @WebMethod
    @RequestWrapper(localName = "removeFederationData", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.RemoveFederationData")
    @ResponseWrapper(localName = "removeFederationDataResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.RemoveFederationDataResponse")
    public void removeFederationData(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId);

    /**
     * 
     * @param roleId
     * @param userId
     * @param departmentIdList
     */
    @WebMethod
    @RequestWrapper(localName = "removeRoleAssignment", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.RemoveRoleAssignment")
    @ResponseWrapper(localName = "removeRoleAssignmentResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.RemoveRoleAssignmentResponse")
    public void removeRoleAssignment(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId,
        @WebParam(name = "roleId", targetNamespace = "")
        Long roleId,
        @WebParam(name = "departmentIdList", targetNamespace = "")
        String departmentIdList);

    /**
     * 
     * @param tagTypeName
     * @param tagName
     * @param userId
     * @param departmentIdList
     */
    @WebMethod
    @RequestWrapper(localName = "removeRolesWithTag", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.RemoveRolesWithTag")
    @ResponseWrapper(localName = "removeRolesWithTagResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.RemoveRolesWithTagResponse")
    public void removeRolesWithTag(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId,
        @WebParam(name = "tagName", targetNamespace = "")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "")
        String tagTypeName,
        @WebParam(name = "departmentIdList", targetNamespace = "")
        String departmentIdList);

    /**
     * 
     * @param tagTypeName
     * @param tagName
     * @param userId
     */
    @WebMethod
    @RequestWrapper(localName = "removeTag", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.RemoveTag")
    @ResponseWrapper(localName = "removeTagResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.RemoveTagResponse")
    public void removeTag(
        @WebParam(name = "userId", targetNamespace = "http://ws.mrted.com/")
        Long userId,
        @WebParam(name = "tagName", targetNamespace = "http://ws.mrted.com/")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

    /**
     * 
     * @param user
     */
    @WebMethod
    @RequestWrapper(localName = "updateUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.UpdateUser")
    @ResponseWrapper(localName = "updateUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.UpdateUserResponse")
    public void updateUser(
        @WebParam(name = "user", targetNamespace = "")
        UserExtDto user);

    /**
     * 
     * @param userLogin
     * @param userId
     */
    @WebMethod
    @RequestWrapper(localName = "deleteUser", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.DeleteUser")
    @ResponseWrapper(localName = "deleteUserResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.DeleteUserResponse")
    public void deleteUser(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId,
        @WebParam(name = "userLogin", targetNamespace = "")
        String userLogin);

    /**
     * 
     * @param langCode
     * @return
     *     returns java.util.List<com.mrted.ws.user.PasswordRules>
     */
    @WebMethod
    @WebResult(name = "passwordRules", targetNamespace = "")
    @RequestWrapper(localName = "getPasswordRules", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetPasswordRules")
    @ResponseWrapper(localName = "getPasswordRulesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetPasswordRulesResponse")
    public List<PasswordRules> getPasswordRules(
        @WebParam(name = "langCode", targetNamespace = "")
        LangCode langCode);

    /**
     * 
     * @param passwordRules
     * @return
     *     returns java.util.List<com.mrted.ws.user.PasswordRuleValidation>
     */
    @WebMethod
    @WebResult(name = "passwordRuleValidation", targetNamespace = "")
    @RequestWrapper(localName = "updatePasswordRules", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.UpdatePasswordRules")
    @ResponseWrapper(localName = "updatePasswordRulesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.UpdatePasswordRulesResponse")
    public List<PasswordRuleValidation> updatePasswordRules(
        @WebParam(name = "passwordRules", targetNamespace = "")
        List<PasswordRules> passwordRules);

    /**
     * 
     * @param roleId
     * @param departmentId
     * @param roleName
     * @param login
     * @param userId
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "deleteRoles", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.DeleteRoles")
    @ResponseWrapper(localName = "deleteRolesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.DeleteRolesResponse")
    public void deleteRoles(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "roleId", targetNamespace = "")
        List<Long> roleId,
        @WebParam(name = "roleName", targetNamespace = "")
        List<String> roleName,
        @WebParam(name = "departmentId", targetNamespace = "")
        Long departmentId);

    /**
     * 
     * @param roleId
     * @param departmentId
     * @param roleName
     * @param login
     * @param userId
     * @param email
     */
    @WebMethod
    @RequestWrapper(localName = "assignRoles", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.AssignRoles")
    @ResponseWrapper(localName = "assignRolesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.AssignRolesResponse")
    public void assignRoles(
        @WebParam(name = "userId", targetNamespace = "")
        Long userId,
        @WebParam(name = "login", targetNamespace = "")
        String login,
        @WebParam(name = "email", targetNamespace = "")
        String email,
        @WebParam(name = "roleId", targetNamespace = "")
        List<Long> roleId,
        @WebParam(name = "roleName", targetNamespace = "")
        List<String> roleName,
        @WebParam(name = "departmentId", targetNamespace = "")
        Long departmentId);

    /**
     * 
     * @param departmentId
     * @return
     *     returns java.util.List<com.mrted.ws.user.UserRightDto>
     */
    @WebMethod
    @WebResult(name = "rights", targetNamespace = "")
    @RequestWrapper(localName = "getRightsWithLabels", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetRightsWithLabels")
    @ResponseWrapper(localName = "getRightsWithLabelsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.user.GetRightsWithLabelsResponse")
    public List<UserRightDto> getRightsWithLabels(
        @WebParam(name = "departmentId", targetNamespace = "")
        Long departmentId);

}
