
package eduhk.fhr.web.soap.candidate;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.ws.Holder;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CandidateWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CandidateWebService {


    /**
     * 
     * @param departmentId
     * @param tagTypeName
     * @param candidateId
     * @param tagName
     */
    @WebMethod
    @RequestWrapper(localName = "addTag", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.AddTag")
    @ResponseWrapper(localName = "addTagResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.AddTagResponse")
    public void addTag(
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId,
        @WebParam(name = "tagName", targetNamespace = "http://ws.mrted.com/")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName,
        @WebParam(name = "departmentId", targetNamespace = "http://ws.mrted.com/")
        Long departmentId);

    /**
     * 
     * @param candidate
     * @param folderId
     */
    @WebMethod
    @RequestWrapper(localName = "createCandidateViaFolder", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.CreateCandidateViaFolder")
    @ResponseWrapper(localName = "createCandidateViaFolderResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.CreateCandidateViaFolderResponse")
    public void createCandidateViaFolder(
        @WebParam(name = "candidate", targetNamespace = "http://ws.mrted.com/", mode = WebParam.Mode.INOUT)
        Holder<Profile> candidate,
        @WebParam(name = "folderId", targetNamespace = "http://ws.mrted.com/")
        Long folderId);

    /**
     * 
     * @param candidate
     * @param jobNumber
     */
    @WebMethod
    @RequestWrapper(localName = "createCandidateViaJobNumber", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.CreateCandidateViaJobNumber")
    @ResponseWrapper(localName = "createCandidateViaJobNumberResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.CreateCandidateViaJobNumberResponse")
    public void createCandidateViaJobNumber(
        @WebParam(name = "candidate", targetNamespace = "http://ws.mrted.com/", mode = WebParam.Mode.INOUT)
        Holder<Profile> candidate,
        @WebParam(name = "jobNumber", targetNamespace = "http://ws.mrted.com/")
        String jobNumber);

    /**
     * 
     * @param candidate
     * @param openingId
     */
    @WebMethod
    @RequestWrapper(localName = "createCandidateViaOpening", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.CreateCandidateViaOpening")
    @ResponseWrapper(localName = "createCandidateViaOpeningResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.CreateCandidateViaOpeningResponse")
    public void createCandidateViaOpening(
        @WebParam(name = "candidate", targetNamespace = "http://ws.mrted.com/", mode = WebParam.Mode.INOUT)
        Holder<Profile> candidate,
        @WebParam(name = "openingId", targetNamespace = "http://ws.mrted.com/")
        Long openingId);

    /**
     * 
     * @param documentId
     * @return
     *     returns eduhk.fhr.web.soap.candidate.AttachedFileDto
     */
    @WebMethod
    @WebResult(name = "attachedFile", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "downloadAttachedFile", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.DownloadAttachedFile")
    @ResponseWrapper(localName = "downloadAttachedFileResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.DownloadAttachedFileResponse")
    public AttachedFileDto downloadAttachedFile(
        @WebParam(name = "documentId", targetNamespace = "http://ws.mrted.com/")
        Long documentId);

    /**
     * 
     * @param editTag
     * @return
     *     returns eduhk.fhr.web.soap.candidate.EditTagByCandidateIDResponse
     */
    @WebMethod
    @WebResult(name = "editTagResponse", targetNamespace = "http://ws.mrted.com/", partName = "editTagResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public EditTagByCandidateIDResponse editTagByCandidateID(
        @WebParam(name = "editTag", targetNamespace = "http://ws.mrted.com/", partName = "editTag")
        EditTagByCandidateID editTag);

    /**
     * 
     * @param applicationId
     * @param displayConsents
     * @return
     *     returns eduhk.fhr.web.soap.candidate.ApplicationDto
     */
    @WebMethod
    @WebResult(name = "application", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getApplicationById", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationById")
    @ResponseWrapper(localName = "getApplicationByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationByIdResponse")
    public ApplicationDto getApplicationById(
        @WebParam(name = "applicationId", targetNamespace = "http://ws.mrted.com/")
        Long applicationId,
        @WebParam(name = "displayConsents", targetNamespace = "http://ws.mrted.com/")
        Boolean displayConsents);

    /**
     * 
     * @param filter
     * @param page
     * @param displayConsents
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.ApplicationDto>
     */
    @WebMethod
    @WebResult(name = "application", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getApplications", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplications")
    @ResponseWrapper(localName = "getApplicationsResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationsResponse")
    public List<ApplicationDto> getApplications(
        @WebParam(name = "page", targetNamespace = "http://ws.mrted.com/")
        Integer page,
        @WebParam(name = "filter", targetNamespace = "http://ws.mrted.com/")
        String filter,
        @WebParam(name = "displayConsents", targetNamespace = "http://ws.mrted.com/")
        Boolean displayConsents);

    /**
     * 
     * @param candidateId
     * @param displayConsents
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.ApplicationDto>
     */
    @WebMethod
    @WebResult(name = "application", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getApplicationsByCandidateId", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationsByCandidateId")
    @ResponseWrapper(localName = "getApplicationsByCandidateIdResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationsByCandidateIdResponse")
    public List<ApplicationDto> getApplicationsByCandidateId(
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId,
        @WebParam(name = "displayConsents", targetNamespace = "http://ws.mrted.com/")
        Boolean displayConsents);

    /**
     * 
     * @param jobId
     * @param page
     * @param jobNumber
     * @param displayConsents
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.ApplicationDto>
     */
    @WebMethod
    @WebResult(name = "applications", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getApplicationsByJob", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationsByJob")
    @ResponseWrapper(localName = "getApplicationsByJobResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationsByJobResponse")
    public List<ApplicationDto> getApplicationsByJob(
        @WebParam(name = "jobId", targetNamespace = "http://ws.mrted.com/")
        Long jobId,
        @WebParam(name = "jobNumber", targetNamespace = "http://ws.mrted.com/")
        String jobNumber,
        @WebParam(name = "page", targetNamespace = "http://ws.mrted.com/")
        Integer page,
        @WebParam(name = "displayConsents", targetNamespace = "http://ws.mrted.com/")
        Boolean displayConsents);

    /**
     * 
     * @param page
     * @param status
     * @param updatedAt
     * @param displayConsents
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.ApplicationDto>
     */
    @WebMethod
    @WebResult(name = "application", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getApplicationsByStatus", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationsByStatus")
    @ResponseWrapper(localName = "getApplicationsByStatusResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetApplicationsByStatusResponse")
    public List<ApplicationDto> getApplicationsByStatus(
        @WebParam(name = "page", targetNamespace = "http://ws.mrted.com/")
        Integer page,
        @WebParam(name = "status", targetNamespace = "http://ws.mrted.com/")
        String status,
        @WebParam(name = "updatedAt", targetNamespace = "http://ws.mrted.com/")
        XMLGregorianCalendar updatedAt,
        @WebParam(name = "displayConsents", targetNamespace = "http://ws.mrted.com/")
        Boolean displayConsents);

    /**
     * 
     * @param archivedCandidatesFilters
     * @param page
     * @return
     *     returns java.util.List<java.lang.Long>
     */
    @WebMethod
    @WebResult(name = "id", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getArchivedCandidates", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetArchivedCandidates")
    @ResponseWrapper(localName = "getArchivedCandidatesResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetArchivedCandidatesResponse")
    public List<Long> getArchivedCandidates(
        @WebParam(name = "archivedCandidatesFilters", targetNamespace = "http://ws.mrted.com/")
        ArchivedCandidatesFiltersDto archivedCandidatesFilters,
        @WebParam(name = "page", targetNamespace = "http://ws.mrted.com/")
        int page);

    /**
     * 
     * @param displayBoTags
     * @param candidateId
     * @param displayConsents
     * @return
     *     returns eduhk.fhr.web.soap.candidate.Profile
     */
    @WebMethod
    @WebResult(name = "candidate", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getCandidateById", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCandidateById")
    @ResponseWrapper(localName = "getCandidateByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCandidateByIdResponse")
    public Profile getCandidateById(
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId,
        @WebParam(name = "displayConsents", targetNamespace = "http://ws.mrted.com/")
        Boolean displayConsents,
        @WebParam(name = "displayBoTags", targetNamespace = "http://ws.mrted.com/")
        Boolean displayBoTags);

    /**
     * 
     * @param candidate
     * @param page
     * @return
     *     returns eduhk.fhr.web.soap.candidate.CandidateIdsDTO
     */
    @WebMethod
    @WebResult(name = "candidates", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getCandidates", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCandidates")
    @ResponseWrapper(localName = "getCandidatesResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCandidatesResponse")
    public CandidateIdsDTO getCandidates(
        @WebParam(name = "page", targetNamespace = "http://ws.mrted.com/")
        Integer page,
        @WebParam(name = "candidate", targetNamespace = "http://ws.mrted.com/")
        CandidateSearchCriteriaDTO candidate);

    /**
     * 
     * @param candidate
     * @param filters
     * @return
     *     returns eduhk.fhr.web.soap.candidate.CandidateHistoryDto
     */
    @WebMethod
    @WebResult(name = "candidateHistory", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getCandidateHistory", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCandidateHistory")
    @ResponseWrapper(localName = "getCandidateHistoryResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCandidateHistoryResponse")
    public CandidateHistoryDto getCandidateHistory(
        @WebParam(name = "candidate", targetNamespace = "http://ws.mrted.com/")
        CandidateHistorySearchCriteriaDto candidate,
        @WebParam(name = "filters", targetNamespace = "http://ws.mrted.com/")
        CandidateHistoryFiltersDto filters);

    /**
     * 
     * @param localizedValueLangCode
     * @param showLocalizedValue
     * @param candidateId
     * @return
     *     returns eduhk.fhr.web.soap.candidate.StructuredDocumentDto
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getCandidateStructuredDocumentById", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCandidateStructuredDocumentById")
    @ResponseWrapper(localName = "getCandidateStructuredDocumentByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCandidateStructuredDocumentByIdResponse")
    public StructuredDocumentDto getCandidateStructuredDocumentById(
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId,
        @WebParam(name = "showLocalizedValue", targetNamespace = "")
        Boolean showLocalizedValue,
        @WebParam(name = "localizedValueLangCode", targetNamespace = "http://ws.mrted.com/")
        LangCode localizedValueLangCode);

    /**
     * 
     * @param filter
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.DpConsentDto>
     */
    @WebMethod
    @WebResult(name = "dpConsentDto", targetNamespace = "")
    @RequestWrapper(localName = "getConsents", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetConsents")
    @ResponseWrapper(localName = "getConsentsResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetConsentsResponse")
    public List<DpConsentDto> getConsents(
        @WebParam(name = "filter", targetNamespace = "http://ws.mrted.com/")
        ConsentSearchCriteriaDto filter);

    /**
     * 
     * @param filter
     * @param page
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.ContractDto>
     */
    @WebMethod
    @WebResult(name = "contract", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getContracts", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetContracts")
    @ResponseWrapper(localName = "getContractsResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetContractsResponse")
    public List<ContractDto> getContracts(
        @WebParam(name = "page", targetNamespace = "http://ws.mrted.com/")
        Integer page,
        @WebParam(name = "filter", targetNamespace = "http://ws.mrted.com/")
        String filter);

    /**
     * 
     * @param applicationId
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.ContractDto>
     */
    @WebMethod
    @WebResult(name = "contract", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getContractsByApplicationId", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetContractsByApplicationId")
    @ResponseWrapper(localName = "getContractsByApplicationIdResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetContractsByApplicationIdResponse")
    public List<ContractDto> getContractsByApplicationId(
        @WebParam(name = "applicationId", targetNamespace = "http://ws.mrted.com/")
        Long applicationId);

    /**
     * 
     * @param detailedSearchCriteriaDto
     * @return
     *     returns eduhk.fhr.web.soap.candidate.DetailedApplicationDto
     */
    @WebMethod
    @WebResult(name = "detailedApplicationDto", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getDetailedApplicants", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetDetailedApplicants")
    @ResponseWrapper(localName = "getDetailedApplicantsResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetDetailedApplicantsResponse")
    public DetailedApplicationDto getDetailedApplicants(
        @WebParam(name = "detailedSearchCriteriaDto", targetNamespace = "http://ws.mrted.com/")
        DetailedSearchCriteriaDto detailedSearchCriteriaDto);

    /**
     * 
     * @param templateType
     * @param localizedValueLangCode
     * @param showLocalizedValue
     * @return
     *     returns eduhk.fhr.web.soap.candidate.FormDto
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getCurrentBoCpTemplateByType", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCurrentBoCpTemplateByType")
    @ResponseWrapper(localName = "getCurrentBoCpTemplateByTypeResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetCurrentBoCpTemplateByTypeResponse")
    public FormDto getCurrentBoCpTemplateByType(
        @WebParam(name = "templateType", targetNamespace = "http://ws.mrted.com/")
        String templateType,
        @WebParam(name = "showLocalizedValue", targetNamespace = "")
        Boolean showLocalizedValue,
        @WebParam(name = "localizedValueLangCode", targetNamespace = "http://ws.mrted.com/")
        LangCode localizedValueLangCode);

    /**
     * 
     * @param candidateId
     * @return
     *     returns eduhk.fhr.web.soap.candidate.CandidateProfile
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getGfCandidateProfile", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetGfCandidateProfile")
    @ResponseWrapper(localName = "getGfCandidateProfileResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetGfCandidateProfileResponse")
    public CandidateProfile getGfCandidateProfile(
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId);

    /**
     * 
     * @param candidateId
     * @return
     *     returns eduhk.fhr.web.soap.candidate.StructuredDocument
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getStructuredDocumentById", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetStructuredDocumentById")
    @ResponseWrapper(localName = "getStructuredDocumentByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetStructuredDocumentByIdResponse")
    public StructuredDocument getStructuredDocumentById(
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId);

    /**
     * 
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.TagType>
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTagTypes", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetTagTypes")
    @ResponseWrapper(localName = "getTagTypesResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetTagTypesResponse")
    public List<TagType> getTagTypes();

    /**
     * 
     * @param tagTypeName
     * @param tagName
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.Profile>
     */
    @WebMethod
    @WebResult(name = "candidate", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTaggedProfiles", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetTaggedProfiles")
    @ResponseWrapper(localName = "getTaggedProfilesResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetTaggedProfilesResponse")
    public List<Profile> getTaggedProfiles(
        @WebParam(name = "tagName", targetNamespace = "http://ws.mrted.com/")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

    /**
     * 
     * @param tagTypeName
     * @return
     *     returns java.util.List<eduhk.fhr.web.soap.candidate.Tag>
     */
    @WebMethod
    @WebResult(name = "tag", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTagsForType", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetTagsForType")
    @ResponseWrapper(localName = "getTagsForTypeResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.GetTagsForTypeResponse")
    public List<Tag> getTagsForType(
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

    /**
     * 
     * @param removeTag
     * @return
     *     returns eduhk.fhr.web.soap.candidate.RemoveTagByCandidateIDResponse
     */
    @WebMethod
    @WebResult(name = "removeTagResponse", targetNamespace = "http://ws.mrted.com/", partName = "removeTagResponse")
    @SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
    public RemoveTagByCandidateIDResponse removeTagByCandidateID(
        @WebParam(name = "removeTag", targetNamespace = "http://ws.mrted.com/", partName = "removeTag")
        RemoveTagByCandidateID removeTag);

    /**
     * 
     * @param formAnsweredDto
     * @param candidateId
     * @throws WebServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "updateCandidatePif", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.UpdateCandidatePif")
    @ResponseWrapper(localName = "updateCandidatePifResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.UpdateCandidatePifResponse")
    public void updateCandidatePif(
        @WebParam(name = "formAnsweredDto", targetNamespace = "http://ws.mrted.com/")
        FormAnsweredDto formAnsweredDto,
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId)
        throws WebServiceException
    ;

    /**
     * 
     * @param consentId
     * @param consentType
     * @param comment
     * @param candidateId
     * @param applicationId
     * @throws WebServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "acceptCandidateConsent", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.AcceptCandidateConsent")
    @ResponseWrapper(localName = "acceptCandidateConsentResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.AcceptCandidateConsentResponse")
    public void acceptCandidateConsent(
        @WebParam(name = "consentId", targetNamespace = "http://ws.mrted.com/")
        long consentId,
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId,
        @WebParam(name = "applicationId", targetNamespace = "http://ws.mrted.com/")
        Long applicationId,
        @WebParam(name = "comment", targetNamespace = "http://ws.mrted.com/")
        String comment,
        @WebParam(name = "consentType", targetNamespace = "http://ws.mrted.com/")
        String consentType)
        throws WebServiceException
    ;

    /**
     * 
     * @param consentId
     * @param consentType
     * @param comment
     * @param candidateId
     * @param applicationId
     * @throws WebServiceException
     */
    @WebMethod
    @RequestWrapper(localName = "revokeCandidateConsent", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.RevokeCandidateConsent")
    @ResponseWrapper(localName = "revokeCandidateConsentResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.RevokeCandidateConsentResponse")
    public void revokeCandidateConsent(
        @WebParam(name = "consentId", targetNamespace = "http://ws.mrted.com/")
        long consentId,
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId,
        @WebParam(name = "applicationId", targetNamespace = "http://ws.mrted.com/")
        Long applicationId,
        @WebParam(name = "comment", targetNamespace = "http://ws.mrted.com/")
        String comment,
        @WebParam(name = "consentType", targetNamespace = "http://ws.mrted.com/")
        String consentType)
        throws WebServiceException
    ;

    /**
     * 
     * @param candidateId
     * @param applicationId
     * @param attachedFile
     * @return
     *     returns java.lang.Long
     */
    @WebMethod
    @WebResult(name = "attachedFileId", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "uploadAttachedFile", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.UploadAttachedFile")
    @ResponseWrapper(localName = "uploadAttachedFileResponse", targetNamespace = "http://ws.mrted.com/", className = "eduhk.fhr.web.soap.candidate.UploadAttachedFileResponse")
    public Long uploadAttachedFile(
        @WebParam(name = "attachedFile", targetNamespace = "http://ws.mrted.com/")
        AttachedFileDto attachedFile,
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId,
        @WebParam(name = "applicationId", targetNamespace = "http://ws.mrted.com/")
        Long applicationId);

}
