
package eduhk.fhr.web.soap.candidate;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WebServiceException", targetNamespace = "http://ws.mrted.com/")
public class WebServiceException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private FaultDetails faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WebServiceException(String message, FaultDetails faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WebServiceException(String message, FaultDetails faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.mrted.ws.candidate.FaultDetails
     */
    public FaultDetails getFaultInfo() {
        return faultInfo;
    }

}
