SET DEFINE OFF;
Insert into RDPS.RDPS_EMAIL_TEMPLATE
   (TEMPLATE_ID, NOTIFICATION_STAGE, EMAIL_SUBJECT, EMAIL_BODY, TIMESTAMP, 
    USERSTAMP)
 Values
   (1, 'BOOKING_ACK', 'Acknowledge Success Email', 'Success', TO_DATE('20/8/2025 14:26:34', 'DD/MM/YYYY HH24:MI:SS'), 
    'RDPS');
Insert into RDPS.RDPS_EMAIL_TEMPLATE
   (TEMPLATE_ID, NOTIFICATION_STAGE, EMAIL_SUBJECT, EMAIL_BODY, TIMESTAMP, 
    USERSTAMP)
 Values
   (2, 'CANCEL_ACK', 'Acknowledge Cancel Email', 'Success', TO_DATE('20/8/2025 14:26:34', 'DD/MM/YYYY HH24:MI:SS'), 
    'RDPS');
COMMIT;
