DROP TABLE RDPS.RDPS_LOV_DISTRICT CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_LOV_DISTRICT
(
  DISTRICT_KEY    NUMBER(3),
  DISTRICT_VALUE  VARCHAR2(100 BYTE)            NOT NULL,
  CREATED_BY      VARCHAR2(32 BYTE)             DEFAULT USER                  NOT NULL,
  CREATION_DATE   DATE                          DEFAULT SYSDATE               NOT NULL,
  USERSTAMP       VARCHAR2(32 BYTE)             DEFAULT USER                  NOT NULL,
  TIMESTAMP       DATE                          DEFAULT SYSDATE               NOT NULL
)
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_DISTRICTS_KEY ON RDPS.RDPS_LOV_DISTRICT
(DISTRICT_KEY)
LOGGING
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_LOV_DISTRICT ADD (
  CONSTRAINT PK_DISTRICTS_KEY
  PRIMARY KEY
  (DISTRICT_KEY)
  USING INDEX RDPS.PK_DISTRICTS_KEY
  ENABLE VALIDATE);
