DROP TABLE RDPS.RDPS_SHEDLOCK CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_SHEDLOCK
(
  NAME        VARCHAR2(64 BYTE)                 NOT NULL,
  LOCK_UNTIL  TIMESTAMP(6)                      NOT NULL,
  LOCKED_AT   TIMESTAMP(6)                      NOT NULL,
  LOCKED_BY   VARCHAR2(255 BYTE)                NOT NULL
)
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_SHEDLOCK ON RDPS.RDPS_SHEDLOCK
(NAME)
LOGGING
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_SHEDLOCK ADD (
  CONSTRAINT PK_SHEDLOCK
  PRIMARY KEY
  (NAME)
  USING INDEX RDPS.PK_SHEDLOCK
  ENABLE VALIDATE);
