SET DEFINE OFF;
Insert into RDPS.RDPS_USER_ROLE
   (ROLE, FCN, ACTIVE, TIMESTAMP, USERSTAMP)
 Values
   ('SYSTEM_ADMIN', 'ROLE_ACCESS_RIGHT_SETUP', 'Y', TO_DATE('18/8/2025 8:55:41', 'DD/MM/YYYY HH24:MI:SS'), 'RDPS');
Insert into RDPS.RDPS_USER_ROLE
   (ROLE, FCN, ACTIVE, TIMESTAMP, USERSTAMP)
 Values
   ('HRO_ADMIN', 'ROLE_USE_RDPS', 'Y', TO_DATE('18/8/2025 8:55:41', 'DD/MM/YYYY HH24:MI:SS'), 'RDPS');
COMMIT;
