DROP TABLE RDPS.RDPS_WORK_EXPERIENCE CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_WORK_EXPERIENCE
(
  CANDIDATE_ID        VARCHAR2(20 BYTE)         NOT NULL,
  REQ_NUMBER          VARCHAR2(20 BYTE)         NOT NULL,
  SEQ                 NUMBER                    NOT NULL,
  EMPLOYER_NAME       VARCHAR2(100 BYTE),
  NATURE_OF_BUSINESS  VARCHAR2(50 BYTE),
  POSITION_TITLE      VARCHAR2(100 BYTE),
  CURRENT_JOB         CHAR(1 BYTE),
  MODE_OF_EMPLOYMENT  VARCHAR2(50 BYTE),
  HOURS_PER_WEEK      VARCHAR2(20 BYTE),
  START_DATE          DATE,
  END_DATE            DATE,
  NATURE_OF_DUTIES    VARCHAR2(1000 BYTE),
  CREATED_BY          VARCHAR2(32 BYTE)         DEFAULT USER                  NOT NULL,
  CREATION_DATE       DATE                      DEFAULT SYSDATE               NOT NULL,
  USERSTAMP           VARCHAR2(32 BYTE)         DEFAULT USER                  NOT NULL,
  TIMESTAMP           DATE                      DEFAULT SYSDATE               NOT NULL
)
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_WORK_EXP ON RDPS.RDPS_WORK_EXPERIENCE
(CANDIDATE_ID, REQ_NUMBER, SEQ)
LOGGING
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_WORK_EXPERIENCE ADD (
  CONSTRAINT PK_WORK_EXP
  PRIMARY KEY
  (CANDIDATE_ID, REQ_NUMBER, SEQ)
  USING INDEX RDPS.PK_WORK_EXP
  ENABLE VALIDATE);


ALTER TABLE RDPS.RDPS_WORK_EXPERIENCE ADD (
  CONSTRAINT FK_WORK_EXP 
  FOREIGN KEY (CANDIDATE_ID, REQ_NUMBER) 
  REFERENCES RDPS.RDPS_CANDIDATE (CANDIDATE_ID, REQ_NUMBER)
  ENABLE VALIDATE);
