DROP TABLE RDPS.TEST_SCHEDULE_TABLE CASCADE CONSTRAINTS;

CREATE TABLE RDPS.TEST_SCHEDULE_TABLE
(
  ID               NUMBER,
  DESCRIPTION      VARCHAR2(4000 BYTE),
  EVENT_TIMESTAMP  TIMESTAMP(6)                 DEFAULT SYSTIMESTAMP
)
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;
