
package com.mrted.ws.configfields;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConfigurableFieldWebService", targetNamespace = "http://ws.mrted.com/", wsdlLocation = "https://api5.lumesse-talenthub.com/HRIS/SOAP/ConfigurableFields?wsdl")
@HandlerChain(file="handler-chain.xml")
public class ConfigurableFieldWebService_Service
    extends Service
{

    private final static URL CONFIGURABLEFIELDWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CONFIGURABLEFIELDWEBSERVICE_EXCEPTION;
    private final static QName CONFIGURABLEFIELDWEBSERVICE_QNAME = new QName("http://ws.mrted.com/", "ConfigurableFieldWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api5.lumesse-talenthub.com/HRIS/SOAP/ConfigurableFields?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONFIGURABLEFIELDWEBSERVICE_WSDL_LOCATION = url;
        CONFIGURABLEFIELDWEBSERVICE_EXCEPTION = e;
    }

    public ConfigurableFieldWebService_Service() {
        super(__getWsdlLocation(), CONFIGURABLEFIELDWEBSERVICE_QNAME);
    }

    public ConfigurableFieldWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONFIGURABLEFIELDWEBSERVICE_QNAME, features);
    }

    public ConfigurableFieldWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, CONFIGURABLEFIELDWEBSERVICE_QNAME);
    }

    public ConfigurableFieldWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONFIGURABLEFIELDWEBSERVICE_QNAME, features);
    }

    public ConfigurableFieldWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConfigurableFieldWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConfigurableFieldWebService
     */
    @WebEndpoint(name = "ConfigurableFieldWebServicePort")
    public ConfigurableFieldWebService getConfigurableFieldWebServicePort() {
        return super.getPort(new QName("http://ws.mrted.com/", "ConfigurableFieldWebServicePort"), ConfigurableFieldWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConfigurableFieldWebService
     */
    @WebEndpoint(name = "ConfigurableFieldWebServicePort")
    public ConfigurableFieldWebService getConfigurableFieldWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mrted.com/", "ConfigurableFieldWebServicePort"), ConfigurableFieldWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONFIGURABLEFIELDWEBSERVICE_EXCEPTION!= null) {
            throw CONFIGURABLEFIELDWEBSERVICE_EXCEPTION;
        }
        return CONFIGURABLEFIELDWEBSERVICE_WSDL_LOCATION;
    }

}
