
package com.mrted.ws.configfields;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConfigurableFieldWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConfigurableFieldWebService {


    /**
     * 
     * @param fffData
     * @return
     *     returns com.mrted.ws.configfields.OperationResultDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeFreeFormFieldEntry", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.RemoveFreeFormFieldEntry")
    @ResponseWrapper(localName = "removeFreeFormFieldEntryResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.RemoveFreeFormFieldEntryResponse")
    public OperationResultDto removeFreeFormFieldEntry(
        @WebParam(name = "fff-data", targetNamespace = "")
        FreeFormFieldEntryDto fffData);

    /**
     * 
     * @param lovData
     * @return
     *     returns com.mrted.ws.configfields.OperationResultDto
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "removeLOVEntry", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.RemoveLOVEntry")
    @ResponseWrapper(localName = "removeLOVEntryResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.RemoveLOVEntryResponse")
    public OperationResultDto removeLOVEntry(
        @WebParam(name = "lov-data", targetNamespace = "")
        GenericLovDto lovData);

    /**
     * 
     * @param lovData
     * @return
     *     returns com.mrted.ws.configfields.OperationResultDto
     */
    @WebMethod
    @WebResult(name = "result", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "removeUserDataEntry", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.RemoveUserDataEntry")
    @ResponseWrapper(localName = "removeUserDataEntryResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.RemoveUserDataEntryResponse")
    public OperationResultDto removeUserDataEntry(
        @WebParam(name = "lov-data", targetNamespace = "")
        GenericLovDto lovData);

    /**
     * 
     * @param fffData
     * @return
     *     returns com.mrted.ws.configfields.FreeFormFieldEntryDto
     */
    @WebMethod
    @WebResult(name = "fff-entry", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "setFreeFormFieldEntry", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetFreeFormFieldEntry")
    @ResponseWrapper(localName = "setFreeFormFieldEntryResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetFreeFormFieldEntryResponse")
    public FreeFormFieldEntryDto setFreeFormFieldEntry(
        @WebParam(name = "fff-data", targetNamespace = "")
        FreeFormFieldEntryDto fffData);

    /**
     * 
     * @param lovLabels
     * @return
     *     returns com.mrted.ws.configfields.LovLabelsDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setFreeFormFieldLabels", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetFreeFormFieldLabels")
    @ResponseWrapper(localName = "setFreeFormFieldLabelsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetFreeFormFieldLabelsResponse")
    public LovLabelsDto setFreeFormFieldLabels(
        @WebParam(name = "lov-labels", targetNamespace = "")
        LovLabelsDto lovLabels);

    /**
     * 
     * @param lovData
     * @return
     *     returns com.mrted.ws.configfields.GenericLovDto
     */
    @WebMethod
    @WebResult(name = "lov-entry", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "setLOVEntry", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetLOVEntry")
    @ResponseWrapper(localName = "setLOVEntryResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetLOVEntryResponse")
    public GenericLovDto setLOVEntry(
        @WebParam(name = "lov-data", targetNamespace = "")
        GenericLovDto lovData);

    /**
     * 
     * @param lovLabels
     * @return
     *     returns com.mrted.ws.configfields.LovLabelsDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setLOVLabels", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetLOVLabels")
    @ResponseWrapper(localName = "setLOVLabelsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetLOVLabelsResponse")
    public LovLabelsDto setLOVLabels(
        @WebParam(name = "lov-labels", targetNamespace = "")
        LovLabelsDto lovLabels);

    /**
     * 
     * @param lovData
     * @return
     *     returns com.mrted.ws.configfields.GenericLovDto
     */
    @WebMethod
    @WebResult(name = "lov-entry", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "setUserDataEntry", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetUserDataEntry")
    @ResponseWrapper(localName = "setUserDataEntryResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetUserDataEntryResponse")
    public GenericLovDto setUserDataEntry(
        @WebParam(name = "lov-data", targetNamespace = "")
        GenericLovDto lovData);

    /**
     * 
     * @param lovLabels
     * @return
     *     returns com.mrted.ws.configfields.LovLabelsDto
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "setUserDataLabels", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetUserDataLabels")
    @ResponseWrapper(localName = "setUserDataLabelsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.configfields.SetUserDataLabelsResponse")
    public LovLabelsDto setUserDataLabels(
        @WebParam(name = "lov-labels", targetNamespace = "")
        LovLabelsDto lovLabels);

}
