
package com.mrted.ws.candidate;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CandidateWebService", targetNamespace = "http://ws.mrted.com/", wsdlLocation = "https://api3.lumesse-talenthub.com/HRIS/SOAP/Candidate?wsdl")
@HandlerChain(file="handler-chain.xml")
public class CandidateWebService_Service
    extends Service
{

    private final static URL CANDIDATEWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException CANDIDATEWEBSERVICE_EXCEPTION;
    private final static QName CANDIDATEWEBSERVICE_QNAME = new QName("http://ws.mrted.com/", "CandidateWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api3.lumesse-talenthub.com/HRIS/SOAP/Candidate?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CANDIDATEWEBSERVICE_WSDL_LOCATION = url;
        CANDIDATEWEBSERVICE_EXCEPTION = e;
    }

    public CandidateWebService_Service() {
        super(__getWsdlLocation(), CANDIDATEWEBSERVICE_QNAME);
    }

    public CandidateWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CANDIDATEWEBSERVICE_QNAME, features);
    }

    public CandidateWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, CANDIDATEWEBSERVICE_QNAME);
    }

    public CandidateWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CANDIDATEWEBSERVICE_QNAME, features);
    }

    public CandidateWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CandidateWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CandidateWebService
     */
    @WebEndpoint(name = "CandidateWebServicePort")
    public CandidateWebService getCandidateWebServicePort() {
        return super.getPort(new QName("http://ws.mrted.com/", "CandidateWebServicePort"), CandidateWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CandidateWebService
     */
    @WebEndpoint(name = "CandidateWebServicePort")
    public CandidateWebService getCandidateWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mrted.com/", "CandidateWebServicePort"), CandidateWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CANDIDATEWEBSERVICE_EXCEPTION!= null) {
            throw CANDIDATEWEBSERVICE_EXCEPTION;
        }
        return CANDIDATEWEBSERVICE_WSDL_LOCATION;
    }

}
