
package com.mrted.ws.documents;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DocumentWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DocumentWebService {


    /**
     * 
     * @param documentId
     * @param tagTypeName
     * @param tagName
     */
    @WebMethod
    @RequestWrapper(localName = "addTag", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.AddTag")
    @ResponseWrapper(localName = "addTagResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.AddTagResponse")
    public void addTag(
        @WebParam(name = "documentId", targetNamespace = "http://ws.mrted.com/")
        Long documentId,
        @WebParam(name = "tagName", targetNamespace = "http://ws.mrted.com/")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

    /**
     * 
     * @param documentId
     * @return
     *     returns com.mrted.ws.documents.AttachedFileDto
     */
    @WebMethod
    @WebResult(name = "attachedFile", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "downloadAttachedFile", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.DownloadAttachedFile")
    @ResponseWrapper(localName = "downloadAttachedFileResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.DownloadAttachedFileResponse")
    public AttachedFileDto downloadAttachedFile(
        @WebParam(name = "documentId", targetNamespace = "http://ws.mrted.com/")
        Long documentId);

    /**
     * 
     * @param templateId
     * @return
     *     returns com.mrted.ws.documents.AttachedFileDto
     */
    @WebMethod
    @WebResult(name = "attachedFile", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "downloadSharedDocument", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.DownloadSharedDocument")
    @ResponseWrapper(localName = "downloadSharedDocumentResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.DownloadSharedDocumentResponse")
    public AttachedFileDto downloadSharedDocument(
        @WebParam(name = "templateId", targetNamespace = "http://ws.mrted.com/")
        Long templateId);

    /**
     * 
     * @param applicationId
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getDocumentsByApplicationId", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetDocumentsByApplicationId")
    @ResponseWrapper(localName = "getDocumentsByApplicationIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetDocumentsByApplicationIdResponse")
    public List<Object> getDocumentsByApplicationId(
        @WebParam(name = "applicationId", targetNamespace = "http://ws.mrted.com/")
        Long applicationId);

    /**
     * 
     * @param candidateId
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getDocumentsByCandidateId", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetDocumentsByCandidateId")
    @ResponseWrapper(localName = "getDocumentsByCandidateIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetDocumentsByCandidateIdResponse")
    public List<Object> getDocumentsByCandidateId(
        @WebParam(name = "candidateId", targetNamespace = "http://ws.mrted.com/")
        Long candidateId);

    /**
     * 
     * @param employeeId
     * @param positionAssignId
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getDocumentsByEmployeeId", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetDocumentsByEmployeeId")
    @ResponseWrapper(localName = "getDocumentsByEmployeeIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetDocumentsByEmployeeIdResponse")
    public List<Object> getDocumentsByEmployeeId(
        @WebParam(name = "employeeId", targetNamespace = "http://ws.mrted.com/")
        Long employeeId,
        @WebParam(name = "positionAssignId", targetNamespace = "http://ws.mrted.com/")
        Long positionAssignId);

    /**
     * 
     * @param documentId
     * @return
     *     returns com.mrted.ws.documents.FormAnsweredDto
     */
    @WebMethod
    @WebResult(name = "formAnsweredDto", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getFormAnsweredByDocumentId", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetFormAnsweredByDocumentId")
    @ResponseWrapper(localName = "getFormAnsweredByDocumentIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetFormAnsweredByDocumentIdResponse")
    public FormAnsweredDto getFormAnsweredByDocumentId(
        @WebParam(name = "documentId", targetNamespace = "http://ws.mrted.com/")
        Long documentId);

    /**
     * 
     * @param documentId
     * @return
     *     returns com.mrted.ws.documents.FreeFormDocumentDto
     */
    @WebMethod
    @WebResult(name = "freeFormDocument", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getFreeFormDocumentById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetFreeFormDocumentById")
    @ResponseWrapper(localName = "getFreeFormDocumentByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetFreeFormDocumentByIdResponse")
    public FreeFormDocumentDto getFreeFormDocumentById(
        @WebParam(name = "documentId", targetNamespace = "http://ws.mrted.com/")
        Long documentId);

    /**
     * 
     * @param documentId
     * @return
     *     returns com.mrted.ws.documents.MailDto
     */
    @WebMethod
    @WebResult(name = "mailDocument", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getMailDocumentById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetMailDocumentById")
    @ResponseWrapper(localName = "getMailDocumentByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetMailDocumentByIdResponse")
    public MailDto getMailDocumentById(
        @WebParam(name = "documentId", targetNamespace = "http://ws.mrted.com/")
        Long documentId);

    /**
     * 
     * @param showLocalizedValues
     * @param langCode
     * @param documentId
     * @return
     *     returns com.mrted.ws.documents.StructuredDocument
     */
    @WebMethod
    @WebResult(name = "structuredDocument", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getStructuredDocumentById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetStructuredDocumentById")
    @ResponseWrapper(localName = "getStructuredDocumentByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetStructuredDocumentByIdResponse")
    public StructuredDocument getStructuredDocumentById(
        @WebParam(name = "documentId", targetNamespace = "http://ws.mrted.com/")
        Long documentId,
        @WebParam(name = "showLocalizedValues", targetNamespace = "http://ws.mrted.com/")
        Boolean showLocalizedValues,
        @WebParam(name = "langCode", targetNamespace = "http://ws.mrted.com/")
        LangCode langCode);

    /**
     * 
     * @param documentId
     * @return
     *     returns com.mrted.ws.documents.StructuredDocumentDto
     */
    @WebMethod
    @WebResult(name = "structuredDocumentDto", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getBasicStructuredDocumentDtoById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetBasicStructuredDocumentDtoById")
    @ResponseWrapper(localName = "getBasicStructuredDocumentDtoByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetBasicStructuredDocumentDtoByIdResponse")
    public StructuredDocumentDto getBasicStructuredDocumentDtoById(
        @WebParam(name = "documentId", targetNamespace = "http://ws.mrted.com/")
        Long documentId);

    /**
     * 
     * @return
     *     returns java.util.List<com.mrted.ws.documents.TagType>
     */
    @WebMethod
    @WebResult(name = "type", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTagTypes", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetTagTypes")
    @ResponseWrapper(localName = "getTagTypesResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetTagTypesResponse")
    public List<TagType> getTagTypes();

    /**
     * 
     * @param tagTypeName
     * @param tagName
     * @return
     *     returns java.util.List<java.lang.Object>
     */
    @WebMethod
    @WebResult(name = "document", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTaggedDocuments", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetTaggedDocuments")
    @ResponseWrapper(localName = "getTaggedDocumentsResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetTaggedDocumentsResponse")
    public List<Object> getTaggedDocuments(
        @WebParam(name = "tagName", targetNamespace = "http://ws.mrted.com/")
        String tagName,
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

    /**
     * 
     * @param tagTypeName
     * @return
     *     returns java.util.List<com.mrted.ws.documents.Tag>
     */
    @WebMethod
    @WebResult(name = "tag", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getTagsForType", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetTagsForType")
    @ResponseWrapper(localName = "getTagsForTypeResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.documents.GetTagsForTypeResponse")
    public List<Tag> getTagsForType(
        @WebParam(name = "tagTypeName", targetNamespace = "http://ws.mrted.com/")
        String tagTypeName);

}
