--
-- Table: RDPS_CANDIDATE_DOCUMENT
-- Purpose: Track document sync from TalentLink to SharePoint
-- Author: Development Team
-- Date: 2025-11-26
--

-- Drop existing objects if they exist
DROP TABLE RDPS_CANDIDATE_DOCUMENT CASCADE CONSTRAINTS PURGE;
DROP SEQUENCE RDPS_CANDIDATE_DOCUMENT_SEQ;

-- Create table for tracking candidate documents
CREATE TABLE RDPS_CANDIDATE_DOCUMENT (
    DOC_ID NUMBER PRIMARY KEY,
    CANDIDATE_ID NUMBER NOT NULL,
    TALENTLINK_APP_ID NUMBER,           -- Application ID (context)
    TALENTLINK_DOC_ID NUMBER NOT NULL,  -- Document ID in TalentLink
    FILE_NAME VARCHAR2(500) NOT NULL,
    FILE_SIZE NUMBER,
    DOC_TYPE VARCHAR2(100),             -- From DocumentBaseDto
    SHAREPOINT_FILE_ID VARCHAR2(100),   -- DriveItem.id
    SHAREPOINT_WEB_URL VARCHAR2(1000),  -- DriveItem.webUrl
    SHAREPOINT_FOLDER_PATH VARCHAR2(500), -- e.g., /Candidate_123/
    SYNC_STATUS VARCHAR2(50) NOT NULL,  -- 'SYNCED', 'FAILED', 'SKIPPED'
    SYNC_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ERROR_MESSAGE VARCHAR2(4000),
    CREATED_BY VARCHAR2(100) DEFAULT 'SYSTEM',
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_CAND_DOC_CANDIDATE FOREIGN KEY (CANDIDATE_ID)
        REFERENCES RDPS_CANDIDATE(CANDIDATE_ID),
    CONSTRAINT UK_CAND_DOC_TLK_ID UNIQUE (TALENTLINK_DOC_ID)
);

-- Create sequence for primary key
CREATE SEQUENCE RDPS_CANDIDATE_DOCUMENT_SEQ START WITH 1 INCREMENT BY 1;

-- Create indexes for performance
CREATE INDEX IDX_CAND_DOC_CANDIDATE ON RDPS_CANDIDATE_DOCUMENT(CANDIDATE_ID);
CREATE INDEX IDX_CAND_DOC_STATUS ON RDPS_CANDIDATE_DOCUMENT(SYNC_STATUS);
CREATE INDEX IDX_CAND_DOC_SYNC_DATE ON RDPS_CANDIDATE_DOCUMENT(SYNC_DATE);

-- Add comments
COMMENT ON TABLE RDPS_CANDIDATE_DOCUMENT IS 'Tracks candidate documents synced from TalentLink to SharePoint';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.DOC_ID IS 'Primary key';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.CANDIDATE_ID IS 'Foreign key to RDPS_CANDIDATE';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.TALENTLINK_APP_ID IS 'Application ID from TalentLink (context)';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.TALENTLINK_DOC_ID IS 'Document ID in TalentLink (unique)';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.FILE_NAME IS 'Original file name';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.FILE_SIZE IS 'File size in bytes';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.DOC_TYPE IS 'Document type from TalentLink';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.SHAREPOINT_FILE_ID IS 'SharePoint DriveItem ID';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.SHAREPOINT_WEB_URL IS 'SharePoint web URL';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.SHAREPOINT_FOLDER_PATH IS 'Folder path in SharePoint';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.SYNC_STATUS IS 'Sync status: SYNCED, FAILED, SKIPPED';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.SYNC_DATE IS 'Date/time of sync attempt';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.ERROR_MESSAGE IS 'Error message if sync failed';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.CREATED_BY IS 'User/system that created record';
COMMENT ON COLUMN RDPS_CANDIDATE_DOCUMENT.CREATED_DATE IS 'Record creation timestamp';

-- Grant permissions (adjust as needed for your environment)
-- GRANT SELECT, INSERT, UPDATE, DELETE ON RDPS_CANDIDATE_DOCUMENT TO RDPS_APP_ROLE;
-- GRANT SELECT ON RDPS_CANDIDATE_DOCUMENT_SEQ TO RDPS_APP_ROLE;

-- Show table created
SELECT 'Table RDPS_CANDIDATE_DOCUMENT created successfully' AS STATUS FROM DUAL;
