--------------------------------------------------------
-- Create Missing Tables from Production
-- Created: 2025-12-02
-- Purpose: Add tables that exist in production but not in local
--------------------------------------------------------

-- Create RDPS_OFFER table (parent table for benefits)
CREATE TABLE RDPS_OFFER (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20),
    CANDIDATE_ID VARCHAR2(20),
    OFFER_STATUS VARCHAR2(15),
    PAY_BASIS CHAR(1),
    EMP_DEP VARCHAR2(240),
    TOA VARCHAR2(5),
    FUNC_TITLE VARCHAR2(20),
    BAND CHAR(2),
    GRADE VARCHAR2(20),
    POST VARCHAR2(20),
    CONTRACT_START_DATE DATE,
    CONTRACT_END_DATE DATE,
    PROBATION_LENGTH NUMBER,
    PROBATION_UNITS CHAR(1),
    NOTICE_LENGTH NUMBER,
    NOTICE_UNITS CHAR(1),
    OFFER_REMARKS VARCHAR2(100),
    PROJECT_TITLE VARCHAR2(50),
    MPF CHAR(1),
    SUPERANNUATION CHAR(1),
    PENSION CHAR(1),
    SALARY_AMOUNT NUMBER(38,2),
    GRATUITY_PCT NUMBER(5,2),
    EMP_MODE CHAR(1),
    PLAN_HOURS NUMBER,
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_OFFER PRIMARY KEY (OFFER_ID)
);

-- Create RDPS_BANK_INFO table
CREATE TABLE RDPS_BANK_INFO (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    BANK_CODE VARCHAR2(5),
    BRANCH_CODE VARCHAR2(5),
    ACCOUNT_NO VARCHAR2(10),
    ACCOUNT_NAME VARCHAR2(64),
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_BANK_INFO PRIMARY KEY (OFFER_ID, REQ_NUMBER),
    CONSTRAINT FK_RDPS_BANK_INFO FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_BENEFIT_MAIN table
CREATE TABLE RDPS_BENEFIT_MAIN (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    MEDICAL_BENEFIT VARCHAR2(50),
    DENTAL_BENEFIT VARCHAR2(50),
    HOUSING_BENEFIT VARCHAR2(50),
    PREVENTIVE_CHECKUP VARCHAR2(50),
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_BENEFIT_MAIN PRIMARY KEY (OFFER_ID, REQ_NUMBER),
    CONSTRAINT FK_RDPS_BENEFIT_MAIN_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_BENEFIT_CHILD table
CREATE TABLE RDPS_BENEFIT_CHILD (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    CHILD_SEQ NUMBER(1,0) NOT NULL,
    LAST_NAME VARCHAR2(32),
    FIRST_NAME VARCHAR2(32),
    MEDICAL_BENEFIT VARCHAR2(50),
    DENTAL_BENEFIT VARCHAR2(50),
    HOUSING_BENEFIT VARCHAR2(50),
    PREVENTIVE_CHECKUP VARCHAR2(50),
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_BENEFIT_CHILD PRIMARY KEY (OFFER_ID, REQ_NUMBER, CHILD_SEQ),
    CONSTRAINT FK_RDPS_BENEFIT_CHILD_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_BENEFIT_SPOUSE table
CREATE TABLE RDPS_BENEFIT_SPOUSE (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    FULL_NAME VARCHAR2(64),
    HKID VARCHAR2(15),
    PASSPORT VARCHAR2(20),
    ORG_NAME VARCHAR2(64),
    ORG_NUMBER NUMBER,
    ORG_ADDRESS VARCHAR2(400),
    ORG_POST VARCHAR2(40),
    ORG_DEPT VARCHAR2(40),
    MEDICAL_BENEFIT VARCHAR2(50),
    DENTAL_BENEFIT VARCHAR2(50),
    HOUSING_BENEFIT VARCHAR2(50),
    PREVENTIVE_CHECKUP VARCHAR2(50),
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_BENEFIT_SPOUSE PRIMARY KEY (OFFER_ID, REQ_NUMBER),
    CONSTRAINT FK_RDPS_BENEFIT_SPOUSE_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_LOV_COUNTRY table
CREATE TABLE RDPS_LOV_COUNTRY (
    COUNTRY_KEY CHAR(3) NOT NULL,
    COUNTRY_VALUE VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_COUNTRY_KEY PRIMARY KEY (COUNTRY_KEY)
);

-- Create RDPS_LOV_NATIONALITY table
CREATE TABLE RDPS_LOV_NATIONALITY (
    NATIONALITY_KEY CHAR(3) NOT NULL,
    NATIONALITY_VALUE VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_NATIONALITY_KEY PRIMARY KEY (NATIONALITY_KEY)
);

-- Create RDPS_LOV_PLACE_OF_ORIGIN table
CREATE TABLE RDPS_LOV_PLACE_OF_ORIGIN (
    PLACE_OF_ORIGIN_KEY CHAR(3) NOT NULL,
    PLACE_OF_ORIGIN_VALUE VARCHAR2(100) NOT NULL,
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_PLACE_OF_ORIGIN_KEY PRIMARY KEY (PLACE_OF_ORIGIN_KEY)
);

-- Create RDPS_PERSON_INFO table
CREATE TABLE RDPS_PERSON_INFO (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    PERSON_NUMBER VARCHAR2(20),
    NATIONALITY VARCHAR2(100),
    PLACE_OF_ORIGIN VARCHAR2(100),
    HIGHEST_EDUCATION VARCHAR2(100),
    MARITAL_STATUS VARCHAR2(15),
    STATUS_DATE DATE,
    VISA_ISSUE_DATE DATE,
    VISA_EXPIRY_DATE DATE,
    IMMIGRATION_STATUS VARCHAR2(40),
    HK_ENTRY_DATE DATE,
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_PERSON_INFO PRIMARY KEY (OFFER_ID, REQ_NUMBER),
    CONSTRAINT FK_RDPS_PERSON_INFO_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_PERSON_SPOUSE table
CREATE TABLE RDPS_PERSON_SPOUSE (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    FULL_NAME VARCHAR2(64),
    FIRST_NAME VARCHAR2(32),
    LAST_NAME VARCHAR2(32),
    CHINESE_NAME VARCHAR2(60),
    DATE_OF_BIRTH DATE,
    GENDER CHAR(1),
    HKID VARCHAR2(15),
    PASSPORT VARCHAR2(20),
    NATIONALITY VARCHAR2(100),
    EMAIL VARCHAR2(50),
    PHONE_NO VARCHAR2(20),
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_PERSON_SPOUSE PRIMARY KEY (OFFER_ID, REQ_NUMBER),
    CONSTRAINT FK_RDPS_PERSON_SPOUSE_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_PERSON_CHILD table
CREATE TABLE RDPS_PERSON_CHILD (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    CHILD_SEQ NUMBER(1,0) NOT NULL,
    FULL_NAME VARCHAR2(64),
    FIRST_NAME VARCHAR2(32),
    LAST_NAME VARCHAR2(32),
    CHINESE_NAME VARCHAR2(60),
    DATE_OF_BIRTH DATE,
    GENDER CHAR(1),
    HKID VARCHAR2(15),
    PASSPORT VARCHAR2(20),
    NATIONALITY VARCHAR2(100),
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_PERSON_CHILD PRIMARY KEY (OFFER_ID, REQ_NUMBER, CHILD_SEQ),
    CONSTRAINT FK_RDPS_PERSON_CHILD_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_PERSON_ECP table (Emergency Contact Person)
CREATE TABLE RDPS_PERSON_ECP (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    FULL_NAME VARCHAR2(64),
    PHONE_NO VARCHAR2(20),
    RELATIONSHIP VARCHAR2(30),
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_PERSON_ECP PRIMARY KEY (OFFER_ID, REQ_NUMBER),
    CONSTRAINT FK_RDPS_PERSON_ECP_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_PHOTO_UPLOAD table
CREATE TABLE RDPS_PHOTO_UPLOAD (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    FILE_NAME VARCHAR2(255),
    FILE_TYPE VARCHAR2(50),
    FILE_DATA BLOB,
    UPLOAD_DATE DATE,
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_PHOTO_UPLOAD PRIMARY KEY (OFFER_ID, REQ_NUMBER),
    CONSTRAINT FK_RDPS_PHOTO_UPLOAD_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

-- Create RDPS_TOEBS table (Transfer to Oracle EBS)
CREATE TABLE RDPS_TOEBS (
    OFFER_ID VARCHAR2(20) NOT NULL,
    REQ_NUMBER VARCHAR2(20) NOT NULL,
    CANDIDATE_ID VARCHAR2(20),
    EBS_STATUS VARCHAR2(20),
    EBS_PERSON_ID VARCHAR2(20),
    EBS_MESSAGE VARCHAR2(4000),
    TRANSFER_DATE DATE,
    CREATED_BY VARCHAR2(32) DEFAULT USER NOT NULL,
    CREATION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USERSTAMP VARCHAR2(32) DEFAULT USER NOT NULL,
    TIMESTAMP DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_RDPS_TOEBS PRIMARY KEY (OFFER_ID, REQ_NUMBER),
    CONSTRAINT FK_RDPS_TOEBS_OFFER FOREIGN KEY (OFFER_ID) REFERENCES RDPS_OFFER(OFFER_ID)
);

COMMIT;

PROMPT Missing tables created successfully!
