SET DEFINE OFF;
Insert into RDPS.RDPS_PARAMETER
   (PARAM_CODE, PARAM_VALUE, ACTIVE, TIMESTAMP, USERSTAMP)
 Values
   ('SSO_LOGOUT_URL', 'https://dapplt.eduhk.hk/logout.jsp', 'Y', TO_DATE('18/8/2025 10:20:06', 'DD/MM/YYYY HH24:MI:SS'), 'RDPS');
Insert into RDPS.RDPS_PARAMETER
   (PARAM_CODE, PARAM_VALUE, ACTIVE, TIMESTAMP, USERSTAMP)
 Values
   ('ENVIRONMENT', 'DEVELOPMENT', 'Y', TO_DATE('18/8/2025 10:20:06', 'DD/MM/YYYY HH24:MI:SS'), 'RDPS');
COMMIT;
