-- Sample Study Mode Lookup Values
-- Insert reference data for RDPS_LOV_STUDY_MODE table

INSERT INTO RDPS.RDPS_LOV_STUDY_MODE (STUDY_MODE_KEY, STUDY_MODE_VALUE) VALUES (1, 'Full-time');
INSERT INTO RDPS.RDPS_LOV_STUDY_MODE (STUDY_MODE_KEY, STUDY_MODE_VALUE) VALUES (2, 'Part-time');
INSERT INTO RDPS.RDPS_LOV_STUDY_MODE (STUDY_MODE_KEY, STUDY_MODE_VALUE) VALUES (3, 'Distance Learning');
INSERT INTO RDPS.RDPS_LOV_STUDY_MODE (STUDY_MODE_KEY, STUDY_MODE_VALUE) VALUES (4, 'Evening');
INSERT INTO RDPS.RDPS_LOV_STUDY_MODE (STUDY_MODE_KEY, STUDY_MODE_VALUE) VALUES (5, 'Online');
INSERT INTO RDPS.RDPS_LOV_STUDY_MODE (STUDY_MODE_KEY, STUDY_MODE_VALUE) VALUES (6, 'Mixed Mode');
INSERT INTO RDPS.RDPS_LOV_STUDY_MODE (STUDY_MODE_KEY, STUDY_MODE_VALUE) VALUES (99, 'Other');

COMMIT;

-- Verify the inserts
SELECT COUNT(*) AS total_study_modes FROM RDPS.RDPS_LOV_STUDY_MODE;
