-- Sample District Lookup Values for Hong Kong
-- Insert reference data for RDPS_LOV_DISTRICT table

-- Hong Kong Island Districts
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (1, 'Central and Western');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (2, 'Eastern');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (3, 'Southern');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (4, 'Wan Chai');

-- Kowloon Districts
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (5, 'Kowloon City');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (6, 'Kwun Tong');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (7, 'Sham Shui Po');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (8, 'Wong Tai Sin');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (9, 'Yau Tsim Mong');

-- New Territories Districts
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (10, 'Islands');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (11, 'Kwai Tsing');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (12, 'North');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (13, 'Sai Kung');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (14, 'Sha Tin');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (15, 'Tai Po');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (16, 'Tsuen Wan');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (17, 'Tuen Mun');
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (18, 'Yuen Long');

-- Other
INSERT INTO RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY, DISTRICT_VALUE) VALUES (99, 'Other / Overseas');

COMMIT;

-- Verify the inserts
SELECT COUNT(*) AS total_districts FROM RDPS.RDPS_LOV_DISTRICT;
