DROP TABLE RDPS.RDPS_REFEREE CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_REFEREE
(
  CANDIDATE_ID    VARCHAR2(20 BYTE)             NOT NULL,
  REQ_NUMBER      VARCHAR2(20 BYTE)             NOT NULL,
  SEQ             NUMBER,
  TITLE           VARCHAR2(15 BYTE),
  FIRST_NAME      VARCHAR2(32 BYTE),
  LAST_NAME       VARCHAR2(32 BYTE),
  POSITION_TITLE  VARCHAR2(100 BYTE),
  PHONE_NUMBER    VARCHAR2(20 BYTE),
  EMAIL           VARCHAR2(50 BYTE),
  RELATIONSHIP    VARCHAR2(50 BYTE),
  CREATED_BY      VARCHAR2(32 BYTE)             DEFAULT USER                  NOT NULL,
  CREATION_DATE   DATE                          DEFAULT SYSDATE               NOT NULL,
  USERSTAMP       VARCHAR2(32 BYTE)             DEFAULT USER                  NOT NULL,
  TIMESTAMP       DATE                          DEFAULT SYSDATE               NOT NULL
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_REFEREES ON RDPS.RDPS_REFEREE
(CANDIDATE_ID, REQ_NUMBER, SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_REFEREE ADD (
  CONSTRAINT PK_REFEREES
  PRIMARY KEY
  (CANDIDATE_ID, REQ_NUMBER, SEQ)
  USING INDEX RDPS.PK_REFEREES
  ENABLE VALIDATE);


ALTER TABLE RDPS.RDPS_REFEREE ADD (
  CONSTRAINT FK_REFEREES 
  FOREIGN KEY (CANDIDATE_ID, REQ_NUMBER) 
  REFERENCES RDPS.RDPS_CANDIDATE (CANDIDATE_ID, REQ_NUMBER)
  ENABLE VALIDATE);
