DROP TABLE RDPS.RDPS_EMAIL_TEMPLATE CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_EMAIL_TEMPLATE
(
  TEMPLATE_ID         INTEGER                   NOT NULL,
  NOTIFICATION_STAGE  VARCHAR2(100 CHAR)        NOT NULL,
  EMAIL_SUBJECT       VARCHAR2(1000 CHAR)       NOT NULL,
  EMAIL_BODY          VARCHAR2(4000 CHAR)       NOT NULL,
  CREATED_BY          VARCHAR2(32 CHAR)         DEFAULT USER NOT NULL,
  CREATION_DATE       DATE                      DEFAULT SYSDATE NOT NULL,
  USERSTAMP           VARCHAR2(100 CHAR)        DEFAULT USER NOT NULL,
  TIMESTAMP           DATE                      DEFAULT SYSDATE NOT NULL
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.RDPS_EMAIL_TEMPLATE_PK ON RDPS.RDPS_EMAIL_TEMPLATE
(TEMPLATE_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_EMAIL_TEMPLATE ADD (
  CONSTRAINT RDPS_EMAIL_TEMPLATE_PK
  PRIMARY KEY
  (TEMPLATE_ID)
  USING INDEX RDPS.RDPS_EMAIL_TEMPLATE_PK
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM RDPS_EMAIL_TEMPLATE FOR RDPS.RDPS_EMAIL_TEMPLATE;
