DROP TABLE RDPS.RDPS_EDU_PROF_QUAL CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_EDU_PROF_QUAL
(
  CANDIDATE_ID      VARCHAR2(20 BYTE)           NOT NULL,
  REQ_NUMBER        VARCHAR2(20 BYTE)           NOT NULL,
  SEQ               NUMBER                      NOT NULL,
  INSTITUTION       VARCHAR2(100 BYTE),
  COUNTRY           VARCHAR2(100 BYTE),
  EDU_LEVEL         NUMBER                      NOT NULL,
  STUDY_MODE        NUMBER                      NOT NULL,
  QUAL_AWARD_DESC   NUMBER                      NOT NULL,
  QUAL_AWARD_CLASS  NUMBER                      NOT NULL,
  OTHERS            VARCHAR2(100 BYTE),
  MAJOR_STUDY_AREA  VARCHAR2(100 BYTE),
  START_DATE        DATE,
  DATE_OF_AWARD     DATE,
  CREATED_BY        VARCHAR2(32 BYTE)           DEFAULT USER                  NOT NULL,
  CREATION_DATE     DATE                        DEFAULT SYSDATE               NOT NULL,
  USERSTAMP         VARCHAR2(32 BYTE)           DEFAULT USER                  NOT NULL,
  TIMESTAMP         DATE                        DEFAULT SYSDATE               NOT NULL
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_EDU_PROF_QUAL ON RDPS.RDPS_EDU_PROF_QUAL
(CANDIDATE_ID, REQ_NUMBER, SEQ)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_EDU_PROF_QUAL ADD (
  CONSTRAINT PK_EDU_PROF_QUAL
  PRIMARY KEY
  (CANDIDATE_ID, REQ_NUMBER, SEQ)
  USING INDEX RDPS.PK_EDU_PROF_QUAL
  ENABLE VALIDATE);


ALTER TABLE RDPS.RDPS_EDU_PROF_QUAL ADD (
  CONSTRAINT FK_EDU_LEVEL 
  FOREIGN KEY (EDU_LEVEL) 
  REFERENCES RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY)
  ENABLE VALIDATE
,  CONSTRAINT FK_EDU_PROF_QUAL 
  FOREIGN KEY (CANDIDATE_ID, REQ_NUMBER) 
  REFERENCES RDPS.RDPS_CANDIDATE (CANDIDATE_ID, REQ_NUMBER)
  ENABLE VALIDATE
,  CONSTRAINT FK_QUAL_AWARD_CLASS 
  FOREIGN KEY (QUAL_AWARD_CLASS) 
  REFERENCES RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY)
  ENABLE VALIDATE
,  CONSTRAINT FK_QUAL_AWARD_DESC 
  FOREIGN KEY (QUAL_AWARD_DESC) 
  REFERENCES RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY)
  ENABLE VALIDATE
,  CONSTRAINT FK_STUDY_MODE 
  FOREIGN KEY (STUDY_MODE) 
  REFERENCES RDPS.RDPS_LOV_STUDY_MODE (STUDY_MODE_KEY)
  ENABLE VALIDATE);
