DROP TABLE RDPS.RDPS_SYSTEM_LOG CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_SYSTEM_LOG
(
  ROW_NO       INTEGER,
  LOG_LEVEL    VARCHAR2(20 CHAR),
  LOG_MESSAGE  VARCHAR2(4000 CHAR),
  TIMESTAMP    DATE                             DEFAULT SYSDATE,
  USERSTAMP    VARCHAR2(100 CHAR)               DEFAULT USER
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.RDPS_SYSTEM_LOG_PK ON RDPS.RDPS_SYSTEM_LOG
(ROW_NO)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_SYSTEM_LOG ADD (
  CONSTRAINT RDPS_SYSTEM_LOG_PK
  PRIMARY KEY
  (ROW_NO)
  USING INDEX RDPS.RDPS_SYSTEM_LOG_PK
  ENABLE VALIDATE);


CREATE OR REPLACE PUBLIC SYNONYM RDPS_SYSTEM_LOG FOR RDPS.RDPS_SYSTEM_LOG;
