DROP TABLE RDPS.RDPS_PARAMETER CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_PARAMETER
(
  PARAM_CODE   VARCHAR2(100 CHAR),
  PARAM_VALUE  VARCHAR2(4000 CHAR),
  ACTIVE       VARCHAR2(1 CHAR)                 DEFAULT 'Y',
  TIMESTAMP    DATE                             DEFAULT SYSDATE,
  USERSTAMP    VARCHAR2(100 CHAR)               DEFAULT USER
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;
