DROP TABLE RDPS.RDPS_LOV_QUAL_AWARD_CLASS CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_LOV_QUAL_AWARD_CLASS
(
  QUAL_AWARD_CLASS_KEY    NUMBER(3),
  QUAL_AWARD_CLASS_VALUE  VARCHAR2(100 BYTE)    NOT NULL,
  CREATED_BY              VARCHAR2(32 BYTE)     DEFAULT USER                  NOT NULL,
  CREATION_DATE           DATE                  DEFAULT SYSDATE               NOT NULL,
  USERSTAMP               VARCHAR2(32 BYTE)     DEFAULT USER                  NOT NULL,
  TIMESTAMP               DATE                  DEFAULT SYSDATE               NOT NULL
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_QUAL_AWARD_CLASS_KEY ON RDPS.RDPS_LOV_QUAL_AWARD_CLASS
(QUAL_AWARD_CLASS_KEY)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_LOV_QUAL_AWARD_CLASS ADD (
  CONSTRAINT PK_QUAL_AWARD_CLASS_KEY
  PRIMARY KEY
  (QUAL_AWARD_CLASS_KEY)
  USING INDEX RDPS.PK_QUAL_AWARD_CLASS_KEY
  ENABLE VALIDATE);
