-- Sample Qualification Award Class Lookup Values
-- Insert reference data for RDPS_LOV_QUAL_AWARD_CLASS table

INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (1, 'First Class Honours');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (2, 'Second Class Honours (Upper Division)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (3, 'Second Class Honours (Lower Division)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (4, 'Third Class Honours');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (5, 'Pass');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (6, 'Distinction');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (7, 'Merit');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (8, 'Credit');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (9, 'Pass with Commendation');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (10, 'Grade A');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (11, 'Grade B');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (12, 'Grade C');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (13, 'Grade D');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (14, 'Grade E');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (15, 'Not Applicable');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_CLASS (QUAL_AWARD_CLASS_KEY, QUAL_AWARD_CLASS_VALUE) VALUES (99, 'Other');

COMMIT;

-- Verify the inserts
SELECT COUNT(*) AS total_award_classes FROM RDPS.RDPS_LOV_QUAL_AWARD_CLASS;
