DROP TABLE RDPS.RDPS_LOV_EDU_LEVEL CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_LOV_EDU_LEVEL
(
  EDU_LEVEL_KEY    NUMBER(3),
  EDU_LEVEL_VALUE  VARCHAR2(100 BYTE)           NOT NULL,
  CREATED_BY       VARCHAR2(32 BYTE)            DEFAULT USER                  NOT NULL,
  CREATION_DATE    DATE                         DEFAULT SYSDATE               NOT NULL,
  USERSTAMP        VARCHAR2(32 BYTE)            DEFAULT USER                  NOT NULL,
  TIMESTAMP        DATE                         DEFAULT SYSDATE               NOT NULL
)
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_EDU_LEVEL_KEY ON RDPS.RDPS_LOV_EDU_LEVEL
(EDU_LEVEL_KEY)
LOGGING
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_LOV_EDU_LEVEL ADD (
  CONSTRAINT PK_EDU_LEVEL_KEY
  PRIMARY KEY
  (EDU_LEVEL_KEY)
  USING INDEX RDPS.PK_EDU_LEVEL_KEY
  ENABLE VALIDATE);
