DROP TABLE RDPS.RDPS_OTHER_INFO CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_OTHER_INFO
(
  CANDIDATE_ID             VARCHAR2(20 BYTE)    NOT NULL,
  REQ_NUMBER               VARCHAR2(20 BYTE)    NOT NULL,
  SALARY                   NUMBER,
  NUMBER_OF_MONTHS         NUMBER,
  ALLOWANCE_AMOUNT         NUMBER,
  ALLOWANCE_PCT            NUMBER,
  ALLOWANCE_TYPE           VARCHAR2(15 BYTE),
  ALLOWANCE_NATURE         VARCHAR2(20 BYTE),
  GRATUITY_AMOUNT          NUMBER,
  GRATUITY_BASIC           NUMBER,
  OTHER_BENEFITS           VARCHAR2(255 BYTE),
  SKILLS                   VARCHAR2(255 BYTE),
  NEXT_SALARY_REVIEW_DATE  DATE,
  EXPECTED_SALARY          NUMBER,
  NOTICE_PERIOD            VARCHAR2(50 BYTE),
  DATE_OF_AVAILABILITY     DATE,
  EDUHK_EMPLOYEE           VARCHAR2(10 BYTE),
  STAFF_NUMBER             VARCHAR2(10 BYTE),
  SOURCE_TYPE              VARCHAR2(20 BYTE),
  SOURCE_TYPE_OTHER        VARCHAR2(200 BYTE),
  DCCPR                    VARCHAR2(25 BYTE),
  DCCPR_DETAILS            VARCHAR2(255 BYTE),
  CREATED_BY               VARCHAR2(32 BYTE)    DEFAULT USER                  NOT NULL,
  CREATION_DATE            DATE                 DEFAULT SYSDATE               NOT NULL,
  USERSTAMP                VARCHAR2(32 BYTE)    DEFAULT USER                  NOT NULL,
  TIMESTAMP                DATE                 DEFAULT SYSDATE               NOT NULL
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_OTHER_INFO ON RDPS.RDPS_OTHER_INFO
(CANDIDATE_ID, REQ_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_OTHER_INFO ADD (
  CONSTRAINT PK_OTHER_INFO
  PRIMARY KEY
  (CANDIDATE_ID, REQ_NUMBER)
  USING INDEX RDPS.PK_OTHER_INFO
  ENABLE VALIDATE);


ALTER TABLE RDPS.RDPS_OTHER_INFO ADD (
  CONSTRAINT FK_OTHER_INFO 
  FOREIGN KEY (CANDIDATE_ID, REQ_NUMBER) 
  REFERENCES RDPS.RDPS_CANDIDATE (CANDIDATE_ID, REQ_NUMBER)
  ENABLE VALIDATE);
