DROP TABLE RDPS.RDPS_IMPORT_VALIDATION_ERROR CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_IMPORT_VALIDATION_ERROR
(
  ERROR_ID          NUMBER                      NOT NULL,
  CANDIDATE_ID      VARCHAR2(20 BYTE)           NOT NULL,
  REQ_NUMBER        VARCHAR2(20 BYTE)           NOT NULL,
  ERROR_TYPE        VARCHAR2(50 BYTE)           NOT NULL,
  FIELD_NAME        VARCHAR2(50 BYTE),
  ERROR_MESSAGE     VARCHAR2(500 BYTE)          NOT NULL,
  ERROR_DETAIL      CLOB,
  IMPORT_BATCH_ID   VARCHAR2(50 BYTE),
  CREATED_BY        VARCHAR2(32 BYTE)           DEFAULT USER                  NOT NULL,
  CREATION_DATE     DATE                        DEFAULT SYSDATE               NOT NULL,
  RESOLVED          CHAR(1 BYTE)                DEFAULT 'N'                   NOT NULL,
  RESOLVED_BY       VARCHAR2(32 BYTE),
  RESOLVED_DATE     DATE
)
TABLESPACE USERS
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;

-- Create sequence for error_id
CREATE SEQUENCE RDPS.RDPS_VALIDATION_ERROR_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Create index on candidate_id and req_number for faster lookups
CREATE INDEX RDPS.IDX_VALIDATION_ERROR_CANDIDATE ON RDPS.RDPS_IMPORT_VALIDATION_ERROR
(CANDIDATE_ID, REQ_NUMBER)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

-- Create index on creation_date for time-based queries
CREATE INDEX RDPS.IDX_VALIDATION_ERROR_DATE ON RDPS.RDPS_IMPORT_VALIDATION_ERROR
(CREATION_DATE DESC)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

-- Create index on resolved status for active error queries
CREATE INDEX RDPS.IDX_VALIDATION_ERROR_RESOLVED ON RDPS.RDPS_IMPORT_VALIDATION_ERROR
(RESOLVED)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

-- Add primary key constraint
ALTER TABLE RDPS.RDPS_IMPORT_VALIDATION_ERROR ADD (
  CONSTRAINT PK_VALIDATION_ERROR
  PRIMARY KEY (ERROR_ID)
  ENABLE VALIDATE);

-- Add check constraint for resolved flag
ALTER TABLE RDPS.RDPS_IMPORT_VALIDATION_ERROR ADD (
  CONSTRAINT CHK_VALIDATION_ERROR_RESOLVED
  CHECK (RESOLVED IN ('Y', 'N'))
  ENABLE VALIDATE);
