SET DEFINE OFF;
Insert into RDPS.RDPS_USER_PROFILE
   (CN, ROLE, EFFECTIVE_DATE_FROM, ACTIVE, TIMESTAMP, 
    USERSTAMP)
 Values
   ('fhr-dev-uacct01', 'SYSTEM_ADMIN', TO_DATE('15/8/2025', 'DD/MM/YYYY'), 'Y', TO_DATE('15/8/2025 15:28:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'RDPS');
Insert into RDPS.RDPS_USER_PROFILE
   (CN, ROLE, EFFECTIVE_DATE_FROM, ACTIVE, TIMESTAMP, 
    USERSTAMP)
 Values
   ('fhr-dev-uacct01', 'HRO_ADMIN', TO_DATE('15/8/2025', 'DD/MM/YYYY'), 'Y', TO_DATE('15/8/2025 15:28:51', 'DD/MM/YYYY HH24:MI:SS'), 
    'RDPS');
COMMIT;
