-- Sample Education Level Lookup Values
-- Insert reference data for RDPS_LOV_EDU_LEVEL table

INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (1, 'Primary Education');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (2, 'Secondary Education (Form 1-5)');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (3, 'Secondary Education (Form 6-7)');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (4, 'Certificate');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (5, 'Diploma');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (6, 'Higher Diploma');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (7, 'Associate Degree');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (8, 'Bachelor Degree');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (9, 'Postgraduate Certificate');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (10, 'Postgraduate Diploma');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (11, 'Master Degree');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (12, 'Doctoral Degree (PhD)');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (13, 'Professional Qualification');
INSERT INTO RDPS.RDPS_LOV_EDU_LEVEL (EDU_LEVEL_KEY, EDU_LEVEL_VALUE) VALUES (99, 'Other');

COMMIT;

-- Verify the inserts
SELECT COUNT(*) AS total_education_levels FROM RDPS.RDPS_LOV_EDU_LEVEL;
