-- Sample Qualification Award Description Lookup Values
-- Insert reference data for RDPS_LOV_QUAL_AWARD_DESC table

-- Undergraduate Degrees
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (1, 'Bachelor of Arts (BA)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (2, 'Bachelor of Science (BSc)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (3, 'Bachelor of Education (BEd)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (4, 'Bachelor of Business Administration (BBA)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (5, 'Bachelor of Engineering (BEng)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (6, 'Bachelor of Social Sciences (BSocSc)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (7, 'Bachelor of Laws (LLB)');

-- Postgraduate Degrees
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (10, 'Master of Arts (MA)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (11, 'Master of Science (MSc)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (12, 'Master of Education (MEd)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (13, 'Master of Business Administration (MBA)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (14, 'Master of Philosophy (MPhil)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (15, 'Master of Laws (LLM)');

-- Doctoral Degrees
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (20, 'Doctor of Philosophy (PhD)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (21, 'Doctor of Education (EdD)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (22, 'Doctor of Business Administration (DBA)');

-- Diplomas and Certificates
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (30, 'Higher Diploma');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (31, 'Advanced Diploma');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (32, 'Diploma');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (33, 'Associate Degree');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (34, 'Postgraduate Certificate');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (35, 'Postgraduate Diploma');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (36, 'Professional Certificate');

-- Professional Qualifications
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (40, 'Chartered Accountant (CA)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (41, 'Certified Public Accountant (CPA)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (42, 'Chartered Financial Analyst (CFA)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (43, 'Teaching Qualification');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (44, 'Qualified Teacher Status (QTS)');

-- Secondary School
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (50, 'HKDSE (Hong Kong Diploma of Secondary Education)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (51, 'HKCEE (Hong Kong Certificate of Education Examination)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (52, 'HKALE (Hong Kong Advanced Level Examination)');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (53, 'GCE A-Level');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (54, 'GCE O-Level');
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (55, 'International Baccalaureate (IB)');

-- Other
INSERT INTO RDPS.RDPS_LOV_QUAL_AWARD_DESC (QUAL_AWARD_DESC_KEY, QUAL_AWARD_DESC_VALUE) VALUES (99, 'Other');

COMMIT;

-- Verify the inserts
SELECT COUNT(*) AS total_award_descriptions FROM RDPS.RDPS_LOV_QUAL_AWARD_DESC;
