-- TalentLink SOAP API Configuration Parameters
-- Insert these parameters into RDPS_PARAMETER table
-- Note: RDPS_PARAMETER table uses PARAM_CODE and PARAM_VALUE (not PARAMETER_NAME/DESCRIPTION)

-- SOAP Endpoint URL (default to TalentLink production endpoint)
INSERT INTO RDPS.RDPS_PARAMETER (PARAM_CODE, PARAM_VALUE, ACTIVE, TIMESTAMP, USERSTAMP)
VALUES (
    'TALENTLINK_USER_SOAP_URL',
    'https://api3.lumesse-talenthub.com/User/SOAP/User',
    'Y',
    SYSDATE,
    USER
);

-- Note: Use the same credentials as REST API
-- TALENTLINK_USERNAME, TALENTLINK_PASSWORD, and TALENTLINK_API_KEY should already exist
-- If not, add them:

/*
INSERT INTO RDPS.RDPS_PARAMETER (PARAM_CODE, PARAM_VALUE, ACTIVE, TIMESTAMP, USERSTAMP)
VALUES (
    'TALENTLINK_USERNAME',
    'YOUR_TENANT:YOUR_USERNAME:BO',
    'Y',
    SYSDATE,
    USER
);

INSERT INTO RDPS.RDPS_PARAMETER (PARAM_CODE, PARAM_VALUE, ACTIVE, TIMESTAMP, USERSTAMP)
VALUES (
    'TALENTLINK_PASSWORD',
    'your_password_here',
    'Y',
    SYSDATE,
    USER
);

INSERT INTO RDPS.RDPS_PARAMETER (PARAM_CODE, PARAM_VALUE, ACTIVE, TIMESTAMP, USERSTAMP)
VALUES (
    'TALENTLINK_API_KEY',
    'your-api-key-here',
    'Y',
    SYSDATE,
    USER
);
*/

COMMIT;

-- Verify the parameters
SELECT PARAM_CODE, PARAM_VALUE
FROM RDPS.RDPS_PARAMETER
WHERE PARAM_CODE IN (
    'TALENTLINK_USER_SOAP_URL',
    'TALENTLINK_USERNAME',
    'TALENTLINK_PASSWORD',
    'TALENTLINK_API_KEY'
)
ORDER BY PARAM_CODE;
