DROP TABLE RDPS.RDPS_CANDIDATE CASCADE CONSTRAINTS;

CREATE TABLE RDPS.RDPS_CANDIDATE
(
  CANDIDATE_ID      VARCHAR2(20 BYTE)           NOT NULL,
  REQ_NUMBER        VARCHAR2(20 BYTE)           NOT NULL,
  POST_APPLIED_FOR  VARCHAR2(100 BYTE),
  TITLE             VARCHAR2(15 BYTE),
  LAST_NAME         VARCHAR2(32 BYTE),
  FIRST_NAME        VARCHAR2(32 BYTE),
  CHINESE_NAME      VARCHAR2(60 BYTE),
  DATE_OF_BIRTH     DATE,
  PERM_HK           CHAR(1 BYTE),
  GENDER            CHAR(1 BYTE),
  HKID              VARCHAR2(30 BYTE),
  PASSPORT_NO       VARCHAR2(20 BYTE),
  VISA_REQUIRED     CHAR(1 BYTE),
  ADDRESS_LINE1     VARCHAR2(60 BYTE),
  ADDRESS_LINE2     VARCHAR2(60 BYTE),
  DISTRICT          NUMBER                      NOT NULL,
  PHONE_NUMBER      VARCHAR2(20 BYTE),
  EMAIL             VARCHAR2(50 BYTE),
  CREATED_BY        VARCHAR2(32 BYTE)           DEFAULT USER                  NOT NULL,
  CREATION_DATE     DATE                        DEFAULT SYSDATE               NOT NULL,
  USERSTAMP         VARCHAR2(32 BYTE)           DEFAULT USER                  NOT NULL,
  TIMESTAMP         DATE                        DEFAULT SYSDATE               NOT NULL
)
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE;


CREATE UNIQUE INDEX RDPS.PK_CANDIDATE_COMPOSITE ON RDPS.RDPS_CANDIDATE
(CANDIDATE_ID, REQ_NUMBER)
LOGGING
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE RDPS.RDPS_CANDIDATE ADD (
  CONSTRAINT PK_CANDIDATE_COMPOSITE
  PRIMARY KEY
  (CANDIDATE_ID, REQ_NUMBER)
  USING INDEX RDPS.PK_CANDIDATE_COMPOSITE
  ENABLE VALIDATE);


ALTER TABLE RDPS.RDPS_CANDIDATE ADD (
  CONSTRAINT FK_DISTRICT 
  FOREIGN KEY (DISTRICT) 
  REFERENCES RDPS.RDPS_LOV_DISTRICT (DISTRICT_KEY)
  ENABLE VALIDATE);
