-- RDPS_IMPORT_HISTORY table for tracking data import operations
-- Stores history of candidate imports from TalentLink

DROP TABLE RDPS.RDPS_IMPORT_HISTORY CASCADE CONSTRAINTS;

DROP SEQUENCE RDPS.RDPS_IMPORT_HISTORY_SEQ;

CREATE TABLE RDPS.RDPS_IMPORT_HISTORY
(
  IMPORT_ID             NUMBER                          NOT NULL,
  IMPORT_DATE           TIMESTAMP                       DEFAULT CURRENT_TIMESTAMP,
  TRIGGERED_BY          VARCHAR2(100 BYTE),
  TOTAL_CANDIDATES      NUMBER                          DEFAULT 0,
  SUCCESSFUL_IMPORTS    NUMBER                          DEFAULT 0,
  FAILED_IMPORTS        NUMBER                          DEFAULT 0,
  DURATION_MS           NUMBER,
  LAST_CANDIDATE_ID     VARCHAR2(100 BYTE),
  STATUS                VARCHAR2(50 BYTE),
  ERROR_MESSAGE         VARCHAR2(4000 BYTE),
  CREATED_BY            VARCHAR2(32 BYTE)               DEFAULT USER NOT NULL,
  CREATION_DATE         DATE                            DEFAULT SYSDATE NOT NULL,
  USERSTAMP             VARCHAR2(32 BYTE)               DEFAULT USER NOT NULL,
  TIMESTAMP             DATE                            DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_RDPS_IMPORT_HISTORY PRIMARY KEY (IMPORT_ID)
)
TABLESPACE RDPS_DATA
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING
NOCOMPRESS
NOCACHE;

-- Create sequence for IMPORT_ID
CREATE SEQUENCE RDPS.RDPS_IMPORT_HISTORY_SEQ
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

-- Create index on IMPORT_DATE for faster queries
CREATE INDEX RDPS.IDX_IMPORT_HISTORY_DATE
  ON RDPS.RDPS_IMPORT_HISTORY(IMPORT_DATE DESC)
  TABLESPACE RDPS_DATA;

-- Create index on STATUS for filtering
CREATE INDEX RDPS.IDX_IMPORT_HISTORY_STATUS
  ON RDPS.RDPS_IMPORT_HISTORY(STATUS)
  TABLESPACE RDPS_DATA;

COMMIT;
