
package eduhk.fhr.web.soap.document;

import java.net.MalformedURLException;
import java.net.URL;

import jakarta.jws.HandlerChain;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DocumentWebService", targetNamespace = "http://ws.mrted.com/", wsdlLocation = "https://api3.lumesse-talenthub.com/HRIS/SOAP/Document?wsdl")
// @HandlerChain(file="handler-chain.xml")  // Commented out - handler added programmatically
public class DocumentWebService_Service
    extends Service
{

    private final static URL DOCUMENTWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOCUMENTWEBSERVICE_EXCEPTION;
    private final static QName DOCUMENTWEBSERVICE_QNAME = new QName("http://ws.mrted.com/", "DocumentWebService");

    static {
        // Don't try to load WSDL at initialization - it requires authentication
        // WSDL will be loaded from the endpoint URL set in TalentLinkSOAPDocumentService
        DOCUMENTWEBSERVICE_WSDL_LOCATION = null;
        DOCUMENTWEBSERVICE_EXCEPTION = null;
    }

    public DocumentWebService_Service() {
        super(__getWsdlLocation(), DOCUMENTWEBSERVICE_QNAME);
    }

    public DocumentWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOCUMENTWEBSERVICE_QNAME, features);
    }

    public DocumentWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, DOCUMENTWEBSERVICE_QNAME);
    }

    public DocumentWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOCUMENTWEBSERVICE_QNAME, features);
    }

    public DocumentWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DocumentWebService
     */
    @WebEndpoint(name = "DocumentWebServicePort")
    public DocumentWebService getDocumentWebServicePort() {
        return super.getPort(new QName("http://ws.mrted.com/", "DocumentWebServicePort"), DocumentWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DocumentWebService
     */
    @WebEndpoint(name = "DocumentWebServicePort")
    public DocumentWebService getDocumentWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mrted.com/", "DocumentWebServicePort"), DocumentWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        // Return null - WSDL will be loaded from endpoint URL with authentication
        return null;
    }

}
