
package com.mrted.ws.lovhierarchy;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "LovHierarchyWebService", targetNamespace = "http://ws.mrted.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface LovHierarchyWebService {


    /**
     * 
     * @param id
     * @param uuid
     * @return
     *     returns com.mrted.ws.lovhierarchy.OperationResultDto
     */
    @WebMethod
    @WebResult(name = "deleteHierarchyMember", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "deleteHierarchyMember", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.DeleteHierarchyMember")
    @ResponseWrapper(localName = "deleteHierarchyMemberResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.DeleteHierarchyMemberResponse")
    public OperationResultDto deleteHierarchyMember(
        @WebParam(name = "id", targetNamespace = "")
        Long id,
        @WebParam(name = "uuid", targetNamespace = "")
        String uuid);

    /**
     * 
     * @param hierarchyMemberId
     * @return
     *     returns com.mrted.ws.lovhierarchy.LovHierarchyMemberDto
     */
    @WebMethod
    @WebResult(name = "getLovHierarchyMemberById", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getLovHierarchyMemberById", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetLovHierarchyMemberById")
    @ResponseWrapper(localName = "getLovHierarchyMemberByIdResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetLovHierarchyMemberByIdResponse")
    public LovHierarchyMemberDto getLovHierarchyMemberById(
        @WebParam(name = "hierarchyMemberId", targetNamespace = "")
        Long hierarchyMemberId);

    /**
     * 
     * @param departmentId
     * @param lovId
     * @param lovType
     * @return
     *     returns java.util.List<com.mrted.ws.lovhierarchy.GenericLovForHierarchingDto>
     */
    @WebMethod
    @WebResult(name = "getLovsAvilableForHierarching", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getLovsAvilableForHierarching", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetLovsAvilableForHierarching")
    @ResponseWrapper(localName = "getLovsAvilableForHierarchingResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetLovsAvilableForHierarchingResponse")
    public List<GenericLovForHierarchingDto> getLovsAvilableForHierarching(
        @WebParam(name = "lovType", targetNamespace = "")
        Integer lovType,
        @WebParam(name = "departmentId", targetNamespace = "")
        Long departmentId,
        @WebParam(name = "lovId", targetNamespace = "")
        Long lovId);

    /**
     * 
     * @param language
     * @param destinationLovId
     * @param parentLovs
     * @return
     *     returns java.util.List<com.mrted.ws.lovhierarchy.GenericLovForHierarchingDto>
     */
    @WebMethod
    @WebResult(name = "getLovsByUnlockers", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getLovsByUnlockers", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetLovsByUnlockers")
    @ResponseWrapper(localName = "getLovsByUnlockersResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetLovsByUnlockersResponse")
    public List<GenericLovForHierarchingDto> getLovsByUnlockers(
        @WebParam(name = "destinationLovId", targetNamespace = "")
        Long destinationLovId,
        @WebParam(name = "parentLovs", targetNamespace = "")
        List<Long> parentLovs,
        @WebParam(name = "language", targetNamespace = "")
        String language);

    /**
     * 
     * @param language
     * @param destinationLovId
     * @param parentLovs
     * @param filterDptId
     * @param filterRecType
     * @return
     *     returns java.util.List<com.mrted.ws.lovhierarchy.GenericLovForHierarchingDto>
     */
    @WebMethod
    @WebResult(name = "getLovsByUnlockers", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getLovsByUnlockersWithFilter", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetLovsByUnlockersWithFilter")
    @ResponseWrapper(localName = "getLovsByUnlockersWithFilterResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetLovsByUnlockersWithFilterResponse")
    public List<GenericLovForHierarchingDto> getLovsByUnlockersWithFilter(
        @WebParam(name = "destinationLovId", targetNamespace = "")
        Long destinationLovId,
        @WebParam(name = "parentLovs", targetNamespace = "")
        List<Long> parentLovs,
        @WebParam(name = "language", targetNamespace = "")
        String language,
        @WebParam(name = "filterDptId", targetNamespace = "")
        Long filterDptId,
        @WebParam(name = "filterRecType", targetNamespace = "")
        RecruitmentType filterRecType);

    /**
     * 
     * @param departmentId
     * @param lovType
     * @return
     *     returns java.util.List<com.mrted.ws.lovhierarchy.LovHierarchyMemberDto>
     */
    @WebMethod
    @WebResult(name = "getWholeHierarchy", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "getWholeHierarchy", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetWholeHierarchy")
    @ResponseWrapper(localName = "getWholeHierarchyResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.GetWholeHierarchyResponse")
    public List<LovHierarchyMemberDto> getWholeHierarchy(
        @WebParam(name = "lovType", targetNamespace = "")
        Integer lovType,
        @WebParam(name = "departmentId", targetNamespace = "")
        Long departmentId);

    /**
     * 
     * @param childId
     * @param parentId
     * @return
     *     returns com.mrted.ws.lovhierarchy.LovHierarchyMemberDto
     */
    @WebMethod
    @WebResult(name = "linkHierarchyMembers", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "linkHierarchyMembers", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.LinkHierarchyMembers")
    @ResponseWrapper(localName = "linkHierarchyMembersResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.LinkHierarchyMembersResponse")
    public LovHierarchyMemberDto linkHierarchyMembers(
        @WebParam(name = "parentId", targetNamespace = "")
        Long parentId,
        @WebParam(name = "childId", targetNamespace = "")
        Long childId);

    /**
     * 
     * @param lovId
     * @return
     *     returns com.mrted.ws.lovhierarchy.LovHierarchyMemberDto
     */
    @WebMethod
    @WebResult(name = "makeLovHierarchyMemberFromLov", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "makeLovHierarchyMemberFromLov", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.MakeLovHierarchyMemberFromLov")
    @ResponseWrapper(localName = "makeLovHierarchyMemberFromLovResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.MakeLovHierarchyMemberFromLovResponse")
    public LovHierarchyMemberDto makeLovHierarchyMemberFromLov(
        @WebParam(name = "lovId", targetNamespace = "")
        Long lovId);

    /**
     * 
     * @param childId
     * @param parentId
     * @return
     *     returns com.mrted.ws.lovhierarchy.OperationResultDto
     */
    @WebMethod
    @WebResult(name = "unLinkHierarchyMembers", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "unLinkHierarchyMembers", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.UnLinkHierarchyMembers")
    @ResponseWrapper(localName = "unLinkHierarchyMembersResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.UnLinkHierarchyMembersResponse")
    public OperationResultDto unLinkHierarchyMembers(
        @WebParam(name = "parentId", targetNamespace = "")
        Long parentId,
        @WebParam(name = "childId", targetNamespace = "")
        Long childId);

    /**
     * 
     * @param hlov
     * @return
     *     returns com.mrted.ws.lovhierarchy.OperationResultDto
     */
    @WebMethod
    @WebResult(name = "updateHierarchy", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "updateHierarchy", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.UpdateHierarchy")
    @ResponseWrapper(localName = "updateHierarchyResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.UpdateHierarchyResponse")
    public OperationResultDto updateHierarchy(
        @WebParam(name = "hlov", targetNamespace = "")
        List<LovHierarchyMemberDto> hlov);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.mrted.ws.lovhierarchy.OperationResultDto
     */
    @WebMethod
    @WebResult(name = "updateHierarchyMemberUnlockers", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "updateHierarchyMemberUnlockers", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.UpdateHierarchyMemberUnlockers")
    @ResponseWrapper(localName = "updateHierarchyMemberUnlockersResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.UpdateHierarchyMemberUnlockersResponse")
    public OperationResultDto updateHierarchyMemberUnlockers(
        @WebParam(name = "arg0", targetNamespace = "")
        LovHierarchyMemberDto arg0);

    /**
     * 
     * @param hlov
     * @return
     *     returns com.mrted.ws.lovhierarchy.OperationResultDto
     */
    @WebMethod
    @WebResult(name = "updateSingleHierarchyMember", targetNamespace = "http://ws.mrted.com/")
    @RequestWrapper(localName = "updateSingleHierarchyMember", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.UpdateSingleHierarchyMember")
    @ResponseWrapper(localName = "updateSingleHierarchyMemberResponse", targetNamespace = "http://ws.mrted.com/", className = "com.mrted.ws.lovhierarchy.UpdateSingleHierarchyMemberResponse")
    public OperationResultDto updateSingleHierarchyMember(
        @WebParam(name = "hlov", targetNamespace = "")
        LovHierarchyMemberDto hlov);

}
