
package com.mrted.ws.lovhierarchy;

import java.net.MalformedURLException;
import java.net.URL;

import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "LovHierarchyWebService", targetNamespace = "http://ws.mrted.com/", wsdlLocation = "https://api5.lumesse-talenthub.com/HRIS/SOAP/LovHierarchy?wsdl")
@HandlerChain(file="handler-chain.xml")
public class LovHierarchyWebService_Service
    extends Service
{

    private final static URL LOVHIERARCHYWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException LOVHIERARCHYWEBSERVICE_EXCEPTION;
    private final static QName LOVHIERARCHYWEBSERVICE_QNAME = new QName("http://ws.mrted.com/", "LovHierarchyWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://api5.lumesse-talenthub.com/HRIS/SOAP/LovHierarchy?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        LOVHIERARCHYWEBSERVICE_WSDL_LOCATION = url;
        LOVHIERARCHYWEBSERVICE_EXCEPTION = e;
    }

    public LovHierarchyWebService_Service() {
        super(__getWsdlLocation(), LOVHIERARCHYWEBSERVICE_QNAME);
    }

    public LovHierarchyWebService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), LOVHIERARCHYWEBSERVICE_QNAME, features);
    }

    public LovHierarchyWebService_Service(URL wsdlLocation) {
        super(wsdlLocation, LOVHIERARCHYWEBSERVICE_QNAME);
    }

    public LovHierarchyWebService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, LOVHIERARCHYWEBSERVICE_QNAME, features);
    }

    public LovHierarchyWebService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LovHierarchyWebService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns LovHierarchyWebService
     */
    @WebEndpoint(name = "LovHierarchyWebServicePort")
    public LovHierarchyWebService getLovHierarchyWebServicePort() {
        return super.getPort(new QName("http://ws.mrted.com/", "LovHierarchyWebServicePort"), LovHierarchyWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LovHierarchyWebService
     */
    @WebEndpoint(name = "LovHierarchyWebServicePort")
    public LovHierarchyWebService getLovHierarchyWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.mrted.com/", "LovHierarchyWebServicePort"), LovHierarchyWebService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (LOVHIERARCHYWEBSERVICE_EXCEPTION!= null) {
            throw LOVHIERARCHYWEBSERVICE_EXCEPTION;
        }
        return LOVHIERARCHYWEBSERVICE_WSDL_LOCATION;
    }

}
